### ISSUE TITLE
DataGrid - Error when re-adding items

### ISSUE THREAD

**Issue by supershopping** [enisn/UraniumUI#103]
I removed all items from "Items". When re-adding a new item or binding a new ObservableCollection to "Items", I am getting below error. 
Java.Lang.IllegalStateException: 'The specified child already has a parent. You must call removeView() on the child's parent first.'

**Comment by enisn** [comment]
It seems it's an issue at android level and it might be related to MAUI Core.  

I'll investigate the reason and create an issue to [dotnet/maui](https://github.com/dotnet/maui) if it's related to MAUI SDK.
