### ISSUE TITLE
TextField: BorderColor not applied (until focus/unfocus)

### ISSUE THREAD

**Issue by get-flat** [enisn/UraniumUI#125]
<material:TextField Title="default" />
<material:TextField Title="Red" BorderColor="Red" />
<material:TextField Title="Green" BorderColor="Green"  Keyboard="Numeric" />

[untitled.webm](https://user-images.githubusercontent.com/74671895/203096934-9d20d61f-f33d-4a4b-bdd8-04a3a5ec1cbf.webm)

**Comment by enisn** [comment]
Due to the same reason as #122

**Comment by enisn** [comment]
Thanks for your catch
There was a nasty bug in InputField. It has been just resolved with https://github.com/enisn/UraniumUI/pull/128

I'll release a patch version for v2.0
