### ISSUE TITLE
[Bug][WinUI] InputField outline border too much withespace

### ISSUE THREAD

**Issue by janduldhardt** [enisn/UraniumUI#130]
In WinUI the space between the InputFields Title and the border gets proportional bigger to the Title's length. I think this should be static. You can see it clearly with the "Check-Out" titled and of course the "looooooooooong" titled InputField.

Here is a screenshot:
![image](https://user-images.githubusercontent.com/42645713/203367261-1da6b3e7-2440-4347-8562-80e988664e84.png)

**Comment by enisn** [comment]
Thank you for your report,

It's fixed and deployed in v2.0.3

![image](https://user-images.githubusercontent.com/23705418/203556064-eff5b6bc-53ec-47de-9e0e-1d12df7a8252.png)
