### ISSUE TITLE
TabView can't used in multiple pages

### ISSUE THREAD

**Issue by cube1911** [enisn/UraniumUI#134]
when i add tabview in serval pages , i found all the tabitem will be show together.    i can't new another tabview instance again . 

the problem is very serious， can you fix it quickly ?

**Comment by enisn** [comment]
Can you provide a sample code? How do you add tabs and how you use another instance?

**Comment by enisn** [comment]
I've reproduced the problem. Thanks for reporting it. I'll work on it

**Comment by cube1911** [comment]
example: add tabview in  mainpage.xaml , add another tabview to  notepage.xaml . just use the simple code . you will found all the tabitem add together .
