### ISSUE TITLE
UraniumUI.Material conflicts with CommunityToolkit.Maui.SourceGenerators

### ISSUE THREAD

**Issue by tekinomikata** [enisn/UraniumUI#136]
I don't have CommunityToolkit as far as I know I've looked into the nugets and I could not find it, but still I am getting this conflict I couldn't pin point from where its coming.

I am not even using the timepicker control.

Any ideas?

best regards.

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0436	The type 'ColorAnimationExtensions_TimePicker' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_TimePicker' in 'UraniumUI.Material, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs'.	TestProject (net7.0-android)	F:\Projects\TestProject\TestProject\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\TimePickerTextColorTo.g.shared.cs	41	Active
```

**Comment by enisn** [comment]
UraniumUI uses. version 3.0.0 of communitytoolkit

https://github.com/enisn/UraniumUI/blob/ac2ab07e826b0ba0fb19c0df622070baf8581b08/src/UraniumUI/UraniumUI.csproj#L26

If you're installed it manually into your project with a different version it can make a conflict.

By the way it already comes with UraniumUI, you don't need to add it manually again.

**Comment by tekinomikata** [comment]
Hi @enisn thanks for the answer, "Transitive packages" means the packages that are installed by other nugets correct?

If so it all matches what you're saying and I have 3.0.0 and still get the conflicts.

![image](https://user-images.githubusercontent.com/59887008/203959589-d0e49a19-4fe1-4098-9222-72cafbf20f43.png)

**Comment by tekinomikata** [comment]
In addition I have also tried with the preview in hope it was something todo with .net 6 vs 7 and the result was the same with stable and preview on .net 7

For reference this is what I have in my csproj
```xml
<ItemGroup>
    <PackageReference Include="InputKit.Maui" Version="4.2.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
    <PackageReference Include="UraniumUI.Icons.FontAwesome" Version="2.1.0-pre.2" />
    <PackageReference Include="UraniumUI.Material" Version="2.1.0-pre.2" />
</ItemGroup>
```

**Comment by enisn** [comment]
Can you provide a minimal sample project that reproduces the issue?

**Comment by enisn** [comment]
CommunityToolKit package has been separated, so I'm closing this issue. Feel free to re-open if same error occurs
