### ISSUE TITLE
TreeView nodes don't expand

### ISSUE THREAD

**Issue by Felicity-R** [enisn/UraniumUI#144]
**Steps to repro:**

1. Create an app with a TreeView that has some nodes with children.
I just created a new app from the 'Uranium UI MAUI Blank Template'; added `<material:TreeView ItemsSource="{Binding Nodes}"/>` to the main page; and defined the nodes by copying the 'MyItems' class and Nodes initialization code from the examples in the docs: https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/TreeView
4. Run the app
5. Click on one of the nodes to expand it

**Expected Results:**
You can expand the node and see the children.

**Actual Results:**
I can see a hover state over the chevron for a given node, but when I click it doesn't expand. No error is thrown either it just does nothing.

My sample app to repro: https://github.com/Felicity-R/UraniumTreeViewTest

Tested on Windows 10, 19043.2251

**Comment by LycianSeattle** [comment]
I hit this problem as well on Windows 11. Using a local build of UraniumUI instead of the nuget packages fixed the issue for me. My guess is that it was fixed by #109

**Comment by toxsedyshev** [comment]
@LycianSeattle PR #109 was merged into 2.1 but the bug is still reproduced in 2.1.0 NuGet package.

**Comment by LycianSeattle** [comment]
🤷 idk when the fix happened then. I do know locally referencing the projects instead of NuGet packages worked for me. That was the biggest churn I saw.

**Comment by enisn** [comment]
It might be related to `IsExpandedPropertyName` bindable property.

If the node binding context (nodes in viewmodel) doesn't have a property named `IsExpanded`, expand state couldn't be kept.

I'll investigate it

**Comment by enisn** [comment]
> @LycianSeattle PR #109 was merged into 2.1 but the bug is still reproduced in 2.1.0 NuGet package.

You're right, ButtonView has issues on windows in release mode.

**Comment by enisn** [comment]
Can you try the new HotFix version `2.1.1`? The problem should be solved

**Comment by toxsedyshev** [comment]
@enisn yep 2.1.1 fixed expand handling, but there is a new bug now: nodes with no children show expand button, while shouldn't.

UPD: Ah, sorry, it was me trying to fix `Warning: 'IsLeaf' property not found on 'APIClient.MAUI.App.JsonTreeView.JsonTreeView+JsonTreeViewItem', target property: 'UraniumUI.Material.Controls.TreeViewNodeHolderView.IsLeaf'` by adding `IsLeaf = false`

**Comment by Felicity-R** [comment]
Can confirm 2.1.1 fixed the issue for me too. Thanks for the quick turnaround!
