### ISSUE TITLE
UraniumUI conflicts CommunityToolkit.Maui

### ISSUE THREAD

**Issue by JhowDevBR** [enisn/UraniumUI#145]
Pls help...
Severity	Code	Description	Project	File	Line	Suppression State
Warning	CS0436	The type 'ColorAnimationExtensions_Editor' in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Editor' in 'UraniumUI.Material, Version=2.0.1.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs'.	ChocadeiraES (net7.0-android)	D:\DEV\ChocadeiraES\ChocadeiraES\CommunityToolkit.Maui.SourceGenerators\CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator\EditorTextColorTo.g.shared.cs	41	Active

**Comment by enisn** [comment]
UraniumUI depends on `3.0.0` version of CommunityToolkit

https://github.com/enisn/UraniumUI/blob/de5129c890d2654bd24eea847670abb92a52e185/src/UraniumUI/UraniumUI.csproj#L26

Do you use different version of CommunityToolkit?

**Comment by JhowDevBR** [comment]
no

**Comment by enisn** [comment]
Can you provide a sample project that reproduces this issue?

**Comment by enisn** [comment]
Related to #198

**Comment by StepKie** [comment]
> Related to #198

And #136, they are pretty much exact duplicates - I would close all but one in order to clean up the open issues...

Everyone, before you open a ticket, please be so courteous to at least search/scroll through the open issues. It is not that overwhelming, this is not dotnet/maui  :-P

**Comment by enisn** [comment]
Since CommunityToolKit is in a separated assembly, I'm closing this issue.
