### ISSUE TITLE
.Net 6 support

### ISSUE THREAD

**Issue by rcocks-hl** [enisn/UraniumUI#153]
.Net 6 is the LTS release and will be supported after .net 7 is end of life: https://dotnet.microsoft.com/en-us/platform/support/policy .

Trying to install UraniumUI.Material on a .net 6 application it says it only supports .net 7.

Can .net 6 support be added?

**Comment by enisn** [comment]
v1 supports .net 6

I can try targeting both .net 7 and 6 at the same time. There shouldn't be a breaking change at all
