### ISSUE TITLE
TreeView Android Row 

### ISSUE THREAD

**Issue by adiamante** [enisn/UraniumUI#156]
Hello I love that an open source TreeView exists for Maui (was missing in Xamarin)

I am using Android and I would like to know if there is a way for me to control the row spacing.

The following is my xaml
```
<material:TreeView ItemsSource="{Binding Root.Children}">
    <material:TreeView.ItemTemplate>
        <DataTemplate>
            <Label Text="{Binding Name}" Margin="0" Padding="0" BackgroundColor="Transparent">
                <Label.Triggers>
                    <DataTrigger TargetType="{x:Type Label}" Binding="{Binding IsSelected}" Value="True">
                        <Setter Property="BackgroundColor" Value="Blue" />
                    </DataTrigger>
                </Label.Triggers>
                <Label.GestureRecognizers>
                    <TapGestureRecognizer CommandParameter="{Binding .}" Command="{Binding BindingContext.SelectNodeCommand, Source={RelativeSource AncestorType={x:Type cntl:PatternTreeView}}}" />
                </Label.GestureRecognizers>
            </Label>
        </DataTemplate>
    </material:TreeView.ItemTemplate>
</material:TreeView>
```

The following is my output:
![image](https://user-images.githubusercontent.com/72841758/208827835-78a88d67-2d31-4297-969a-f56b2711eeb4.png)

I have both Margin and Padding set to zero and would like there to be less space in between rows.

**Comment by enisn** [comment]
Can you try `VerticalOptions="Center"` for the Label?

**Comment by adiamante** [comment]
[image: image.png]

**Comment by adiamante** [comment]
In case the image didn't send properly through email

![centered](https://user-images.githubusercontent.com/72841758/208831063-4916912b-e7f0-4dbe-8b87-9b3c9cddd9ca.png)

**Comment by enisn** [comment]
Ok I see, it happens because of Arrow icon margin. It can't be changed outside of component at the moment. I'll make it configurable.

**Comment by enisn** [comment]
You can try the new pre-release version `2.2.0-pre.1` and use **Spacing** property of TreeView at he moment
