### ISSUE TITLE
RadioButton CheckedChange event not found

### ISSUE THREAD

**Issue by YBTopaz8** [enisn/UraniumUI#170]
Hi, 
I was trying to call an event for when the state of my radio button is changed from checked to unchecked (and vice versa)

On the MAUI RadioButton, there exists a CheckedChanged(object sender, CheckedChangedEventArgs e) { }
But to the best of my knowledge, it doesn't exist on Material Radio Buttons..
Here is an image of what I mean..
I was wondering if maybe I looked the wrong way and if there is indeed an implementation for that?
Thanks in advance, and sorry for any inconvenience🙇🏾‍♂️
![image](https://user-images.githubusercontent.com/41630728/209585451-dfca88f2-a2ee-4613-92d9-84c672486a25.png)

**Comment by YBTopaz8** [comment]
So, After looking into the issue once more, I tried a solution that goes as follows:
First, I wrap all my buttons in a RadioGroupView, then I give all of them a value (optional) like this :
![image](https://user-images.githubusercontent.com/41630728/209655746-2e97a39c-1d59-41b5-80c5-1853109bedb5.png)

Then, I use the SelectedItemChanged Event in the RadioGroupView and this way, I'm able to do an action whenever I check another RadioButton, like this:
![image](https://user-images.githubusercontent.com/41630728/209655861-7fb7c985-5ae4-449d-a4d1-9f442c75f971.png)

This approach gets the job done, so I'm quite alright with it. 
Hope this helps anyone and i'm open to any better suggestions!

**Comment by asifsaberi** [comment]
Using the above approach, i have two radiobuttons to allow the user to select the unit of measurement for a calculation. 
I use the selection in codebehind for some math. Here is the code -

    private void RBGSelectedItemChanged(object sender, SelectedItemChangedEventArgs e)
    {
        if (e.SelectedItem == null)
        {
            return;
        }
        var selected = e.SelectedItem as RadioButtonGroupItem;
        if (selected.Text == "Yes")
        {
            dobutamine = 1;
        }
        else
        {
            dobutamine = 0;
        }
    }

However, I get the following error:
CS0246	The type or namespace name 'RadioButtonGroupItem' could not be found (are you missing a using directive or an assembly reference?)	
I am using the directive UraniumUI

Thanks in advance for any assistance solving this.

**Comment by YBTopaz8** [comment]
Hi, I just search and I don't believe there is a control named RadioButtonGroupItem?
There is
`RadioButtonGroupView` from `UraniumUI.Material.Controls.RadioButtonGroupView`
And `RadioButton` from `UraniumUI.Material.Controls.RadioButton`
and even `RadioButtonGroup` from `Microsoft.Maui.Controls.RadioButtonGroup` but no such thing as RadioButtonGroupItem
Where did you get it please?

**Comment by asifsaberi** [comment]
Hi Yvan:
Thanks for responding so quickly.
I apologize if I misstated or misconveyed the problem.
Here is a code snippet (screen shot, followed by code itself) to give you an idea. I am using RadioButtonGroupView to group the radio button. But the "var selected = e.SelectedItem as RadioButtonGroupItem;” in code behind is to assign the selected RadioButton to a variable, to use for a math calculation (it has to do with how a drug is dosed in the ICU. 
Also, I need to reuse this radioButtonGroup for more than one drug in the form. Ay suggestions how I can do this?
Any insights would help me.
Thanks in Advance!
Asif.

Asif A. Saberi, MD, MBA, CPE, FCCP
Diplomate, American Board of Internal Medicine - Pulmonary & Critical Care
Diplomate, American Board of Sleep Medicine
Medical Director, Critical Care Medicine & ECMO
Wellstar Kennestone Regional Medical Center
Clinical Associate Professor of Medicine
Medical College of Georgia at Augusta University

____________________________________

￼





Follow Us:  FACEBOOK <https://www.facebook.com/wellstarhealthsystem>   TWITTER <https://twitter.com/WellStarHealth>   INSTAGRAM <https://www.instagram.com/wellstarhealth>   LINKEDIN <https://www.linkedin.com/company/wellstar-health-system/>   WELLSTAR <https://www.wellstar.org/>. <https://www.wellstar.org/>ORG <https://www.wellstar.org/>
 



￼

<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="iECMO.VIScore"
             xmlns:tk="http://schemas.microsoft.com/dotnet/2022/maui/toolkit"
             xmlns:u="http://schemas.enisn-projects.io/dotnet/maui/uraniumui"
             xmlns:m="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
             xmlns:input="clr-namespace:InputKit.Shared.Controls;assembly=InputKit.Maui"
             xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"
             Title="Vasopressor Inotrope Score">

    <ScrollView Padding="20">
        
        <VerticalStackLayout>
            <HorizontalStackLayout HorizontalOptions="Center">
                <Slider x:Name="slWeight" Margin="10"
                    MaximumWidthRequest="250"
                    Minimum="25"
                    Maximum="250"
                    ValueChanged="slWeight_ValueChanged"/>
                <m:PickerField x:Name="pkWtUnit"
                               Title="Wt Unit"
                               ItemsSource="{Binding Items}"
                               AllowClear="True"
                               HorizontalOptions="StartAndExpand"
                               SelectedValueChanged="pkWtUnit_SelectedValueChanged"/>
            </HorizontalStackLayout>
            <HorizontalStackLayout HorizontalOptions="Center">
                <Label x:Name="lblWeight" 
                    Text="{Binding Source={x:Reference slWeight},
                        Path=Value,
                        StringFormat='Weight {0:0,0} '}"/>
                <Label x:Name="lblWeightUnit"
                    Text="{Binding Source={x:Reference pkWtUnit}, Path=SelectedItem}" />
            </HorizontalStackLayout>

            <BoxView StyleClass="Divider" Margin="10"/>

            <m:TextField x:Name="txtDobutamine"
                         Title="Dobutamine mcg/kg/min"
                         WidthRequest="200" 
                         Keyboard="Numeric">
                <validation:RequiredValidation/>
                <validation:DigitsOnlyValidation/>
            </m:TextField>

            <m:TextField x:Name="txtDopamine"
                         Title="Dopamine mcg/kg/min"
                         WidthRequest="200" 
                         Keyboard="Numeric">
                <validation:RequiredValidation/>
                <validation:DigitsOnlyValidation/>
            </m:TextField>

            <m:TextField x:Name="txtMilrinone" 
                         Title="Milrinone mcg/kg/min"
                         WidthRequest="200" 
                         Keyboard="Numeric">
                <validation:RequiredValidation/>
                <validation:DigitsOnlyValidation/>
            </m:TextField>

            <m:TextField x:Name="txtVasopressin" 
                         Title="Vasopressin Units/min"
                         WidthRequest="200" Keyboard="Numeric">
                <validation:RequiredValidation/>
                <validation:DigitsOnlyValidation/>
            </m:TextField>

            <BoxView StyleClass="Divider" Margin="10"/>

            <HorizontalStackLayout HorizontalOptions="Center">
                <m:TextField x:Name="txtEpinephrine" 
                             Title="Epinephrine" 
                             WidthRequest="200" 
                             Keyboard="Numeric">
                    <validation:RequiredValidation/>
                    <validation:NumericValidation/>
                </m:TextField>
                <m:RadioButtonGroupView 
                    SelectedItemChanged="RBGView_SelectedItemChanged">
                    <m:RadioButton Value="mcg/min" 
                       Text="mcg/min"
                       IsChecked="True"/>
                    <m:RadioButton Value="mcg/kg/min" 
                       Text="mcg/kg/min"/>
                </m:RadioButtonGroupView>
            </HorizontalStackLayout>

            <BoxView StyleClass="Divider" Margin="10"/>

            <HorizontalStackLayout HorizontalOptions="Center">
                <m:TextField x:Name="txtNorepinephrine"
                             Title="Norepinephrine"
                             WidthRequest="200"
                             Keyboard="Numeric">
                    <validation:RequiredValidation/>
                    <validation:NumericValidation/>
                </m:TextField>
                <m:RadioButtonGroupView 
                    SelectedItemChanged="RBGView_SelectedItemChanged">
                    <m:RadioButton Value="mcg/min" 
                                   Text="mcg/min"
                                   IsChecked="True"/>
                    <m:RadioButton Value="mcg/kg/min" 
                                   Text="mcg/kg/min"/>
                </m:RadioButtonGroupView>
            </HorizontalStackLayout>

            <BoxView StyleClass="Divider" Margin="10"/>

            <HorizontalStackLayout HorizontalOptions="Center">
                <m:TextField x:Name="txtPhenylephrine"
                             Title="Phenylephrine"
                             WidthRequest="200"
                             Keyboard="Numeric">
                    <validation:RequiredValidation/>
                    <validation:NumericValidation/>
                </m:TextField>

                <m:RadioButtonGroupView 
                    SelectedItemChanged="RBGView_SelectedItemChanged">
                    <m:RadioButton Value="mcg/min" 
                                   Text="mcg/min"
                                   IsChecked="True"/>
                    <m:RadioButton Value="mcg/kg/min" 
                                   Text="mcg/kg/min"/>
                </m:RadioButtonGroupView>
            </HorizontalStackLayout>

            <BoxView StyleClass="Divider" Margin="10"/>

            <m:TextField Title="Angiotensin-2 mcg/kg/min" 
                         WidthRequest="250"
                         Keyboard="Numeric">
                <validation:RequiredValidation/>
                <validation:NumericValidation/>
            </m:TextField>

            <Button x:Name="btnOK"
                    Margin="20"
                    Text="OK"
                    StyleClass="ElevatedButton"
                    CornerRadius="20"
                    WidthRequest="250"
                    Clicked="btnOK_Clicked"/>

            <BoxView StyleClass="Divider" />

            <u:ExpanderView HorizontalOptions="Center" 
                            Margin="20" 
                            BackgroundColor="AliceBlue">
                <u:ExpanderView.Header>
                    <Label Text="VIS"
                           FontSize="Large"
                           x:Name="lblVIScore"/>
                </u:ExpanderView.Header>
                <Label Margin="10"
                       x:Name="lblInterpretation" />
            </u:ExpanderView>

            <Label
                Text="Reference"
                TextColor="Blue"
                HorizontalOptions="Center">
                <Label.GestureRecognizers>
                    <TapGestureRecognizer 
                        Tapped="TapGestureRecognizer_Tapped"/>
                </Label.GestureRecognizers>
            </Label>
        </VerticalStackLayout>
    </ScrollView>
</ContentPage>

**Comment by YBTopaz8** [comment]
Hi Again @asifsaberi , sorry for the late reply this time around, did you find a solution to this? 
If not, I am interested in know more (like the code behind for example), if possible?
Thanks
