### ISSUE TITLE
StatefulContentView LongPressCommand in Android

### ISSUE THREAD

**Issue by adiamante** [enisn/UraniumUI#171]
I was trying out StatefulContentView.LongPressCommand from the [StatefulContentView docs](https://enisn-projects.io/docs/en/uranium/latest/infrastructure/StatefulContentView#commands) and found that it works properly on Windows but not on Android. I am currently using the LongPress workaround for Android mentioned in [XamarinCommunityToolkit issue #1905](https://github.com/xamarin/XamarinCommunityToolkit/issues/1905) but that does not work on Windows.

```
<uranium:UraniumContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:vm="clr-namespace:YeetMacro2.ViewModels"
             BindingContext="{StaticResource MacroManagerViewModel}"
             vm:ViewModelLocator.ViewModelType="{x:Type vm:MacroManagerViewModel}"
             xmlns:cntl="clr-namespace:YeetMacro2.Controls"
             x:Class="YeetMacro2.Pages.MacroManagerPage"
             xmlns:uuiv="clr-namespace:UraniumUI.Views;assembly=UraniumUI"
             xmlns:uranium="http://schemas.enisn-projects.io/dotnet/maui/uraniumui"
             Title="MacroManagerPage">
    <uuiv:StatefulContentView LongPressCommand="{Binding AddMacroSetCommand}">
        <Grid BackgroundColor="Blue">

        </Grid>
    </uuiv:StatefulContentView>
</uranium:UraniumContentPage>
```

Let me know if this is out of scope. Thank you.

**Comment by enisn** [comment]
It uses the LongClick event of android.
https://github.com/enisn/UraniumUI/blob/7d7039b5030bc635d404512b6e1012be8719808d/src/UraniumUI/Handlers/StatefulContentViewHandler.cs#L38

It works as expected in sample app in the repository with ProjectReference but it doesn't work as you reported with PackageReference. Some might be trimmed in the NuGet package. I'll investigate it

**Comment by adiamante** [comment]
Hi @enisn,

I was able to get get long press command for android after editing [StatefulContentViewHandler.cs](https://github.com/enisn/UraniumUI/blob/7d7039b5030bc635d404512b6e1012be8719808d/src/UraniumUI/Handlers/StatefulContentViewHandler.cs#L38).

Please check out this [pull request](https://github.com/enisn/UraniumUI/pull/247) to see the changes.

Thanks,
Angelo

**Comment by adiamante** [comment]
This has been published. Thanks @enisn
