### ISSUE TITLE
Data Grid Not Filling up the total space or No way to put spaces on Auto Column Any Help ? 

### ISSUE THREAD

**Issue by samirgcofficial** [enisn/UraniumUI#172]
Tried but it fails to set the spaces between the columns, and everything is congested.  
![Screenshot 2022-12-28 185505](https://user-images.githubusercontent.com/55045516/209817888-efdb1bac-3356-48bf-932b-69988db50562.png)

// Tried with this code 

![Screenshot 2022-12-28 190452](https://user-images.githubusercontent.com/55045516/209818493-58a8392d-b5b3-4bea-90a5-a41377109f5e.png)

Platform : Windows

**Comment by samirgcofficial** [comment]
Using UraniumUI Version 0.13.1 
 XAML CODE USED : 
 
![One](https://user-images.githubusercontent.com/55045516/209823457-46e03f41-0c97-4c66-965c-906c5294902f.png)

 Out Put : 
![Screenshot 2022-12-28 194213](https://user-images.githubusercontent.com/55045516/209823064-1a6ec0f6-3e74-4594-8c31-f3226ba6f0ed.png)

Using Uranium Latest Version : 2.2.0 pre-1 
XAML CODE USED : 
![Two](https://user-images.githubusercontent.com/55045516/209824682-f94e5718-ebcb-4657-9cc1-e11ff8244711.png)


Output :  Every Thing is Congested 

![TwoResult](https://user-images.githubusercontent.com/55045516/209824693-8497ed55-dfee-4d36-bfd0-697b113dc49a.png)


Expected Output : The result should be same same as UraniumUI Version 0.13.1

**Comment by enisn** [comment]
I see the difference. But cell rendering logic has been changed since that version. C
- Can you try setting a **Margin** to the TitleTemplate?
- And setting **HorizontalOptions** as `Center` for CellItemTemplate?

In your case it should be something like that:


```xml
<material:DataGrid ItemsSource="{Binding Items}" UseAutoColumns="True" HorizontalOptions="Center" Margin="30">
    <material:DataGrid.TitleTemplate>
        <DataTemplate>
            <Label Margin="10,0" Text="{Binding Value}" FontSize="14" TextColor="Black" />
        </DataTemplate>
    </material:DataGrid.TitleTemplate>
    <material:DataGrid.CellItemTemplate>
        <DataTemplate>
            <VerticalStackLayout HorizontalOptions="Center">
                <Label Text="{Binding Value}"  />
            </VerticalStackLayout>
        </DataTemplate>
    </material:DataGrid.CellItemTemplate>
</material:DataGrid>
```

**Comment by samirgcofficial** [comment]
Yes, Thank you issue was resolved after adding this.
