### ISSUE TITLE
CommunityToolkit.Maui.SourceGenerators namespace clash

### ISSUE THREAD

**Issue by gpproton** [enisn/UraniumUI#198]
I'm not sure if this is a major issue but this warning kept occurring, below are the packages on my project

```xml
<PackageReference Include="BindableProps" Version="1.2.0" />
<PackageReference Include="CommunityToolkit.Maui" Version="3.1.0" />
<PackageReference Include="CommunityToolkit.Maui.Markup" Version="2.1.0" />
<PackageReference Include="CommunityToolkit.Mvvm" Version="8.1.0-preview3" />
<PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="7.0.0" />
<PackageReference Include="Microsoft.Identity.Client" Version="4.46.0" />
<PackageReference Include="Plugin.Maui.Popup" Version="1.0.4" />
<PackageReference Include="UraniumUI.Icons.FontAwesome" Version="2.2.0" />
<PackageReference Include="UraniumUI.Material" Version="2.2.0" />
```

The type 'ColorAnimationExtensions_Picker' in 'CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator/PickerTextColorTo.g.shared.cs' conflicts with the imported type 'ColorAnimationExtensions_Picker' in 'UraniumUI.Material, Version=2.2.0.0, Culture=neutral, PublicKeyToken=null'. Using the type defined in 'CommunityToolkit.Maui.SourceGenerators/CommunityToolkit.Maui.SourceGenerators.Generators.TextColorToGenerator/PickerTextColorTo.g.shared.cs'.

**Comment by enisn** [comment]
You can try removing `CommunityToolkit.Maui` package from your .csproj, UraniumUI already references that package

https://github.com/enisn/UraniumUI/blob/a3b3716625ac5e6db0b0afc9610797ec40c8dbcf/src/UraniumUI/UraniumUI.csproj#L33

**Comment by enisn** [comment]
It seems that source generator is loaded from two different references. CommunityToolkit should separate source generators into different assembly or should create an abstraction package that other libraries can reference to.

**Comment by gpproton** [comment]
As you advised after removing the package reference the warning no longer appears.

Thanks.
