### ISSUE TITLE
[Bug] AutoCompleteTextField Doesn't Display Result in CommunityToolKit Popup

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#204]
Title.

I'll have to make a small sample repo for replication later as I can't post my source code here. I copied the code from the Demo app for AutoCompleteTextField, and the functionality works, but results are not displayed in the UI when using a Popup from the CommunityToolKit.

**Comment by enisn** [comment]
Can you confirm whether that happens on all platforms or just on a specific platform? 

Since iOS doesn't have any suggestbox equivalent implementation and I have a custom implementation for ios.
https://github.com/enisn/UraniumUI/blob/b105b30b5923f9acd44e4b0c99768454f7afb5e6/src/UraniumUI.Material/Handlers/AutoCompleteViewHandler.Apple.cs#L350

**Comment by BinaryAssault** [comment]
> Can you confirm whether that happens on all platforms or just on a specific platform?
> 
> Since iOS doesn't have any suggestbox equivalent implementation and I have a custom implementation for ios.
> 
> https://github.com/enisn/UraniumUI/blob/b105b30b5923f9acd44e4b0c99768454f7afb5e6/src/UraniumUI.Material/Handlers/AutoCompleteViewHandler.Apple.cs#L350

Sorry, forgot to mention. This is on Android, I tested with A7 and A10, both do not work (inside the popup). No suggestions are displayed.

I do not have any apple equipment, so I won't be able to test apple. Also never tested on windows - apparently my APP crashes on desktop. I'll put together a repo replicating the issue hopefully soon.

**Comment by BinaryAssault** [comment]
Can't replicate it in a standalone app. So must be a problem with my code base.

**Comment by BinaryAssault** [comment]
Figured it out, at some point I removed .ToList() from the call below. Adding .ToList() back fixed it
``````
 SearchResults = (await GetSuggestionsAsync(value)).ToList();
``````
