### ISSUE TITLE
[Enhancement] Add SelectedText to AutoCompleteTextField

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#205]
Similar to a Picker control, having a SelectedText BindableProperty would be beneficial IMO

**Comment by BinaryAssault** [comment]
Perusing through the code, I noticed the IAutoCompleteView interface has a completed event that never gets fired by the android platform. Maybe this is a MAUI bug? Event handler looks wired correctly on both the native and C# side. 

``````
// Never gets called when the IME goes away
    private void PlatformView_EditorAction(object sender, TextView.EditorActionEventArgs e)
    {
        if (e.ActionId == Android.Views.InputMethods.ImeAction.Done)
        {
            VirtualView.Completed();
        }
    }
``````

Edit -- 
Seems that `PlatformView.EditorAction += PlatformView_EditorAction` is only called when enter is pushed which doesn't work for selecting an item. That functionality works (pressing enter).

**Comment by BinaryAssault** [comment]
Turns out I just don't fully understand how handlers work. There is no bug related to this in MAUI or Uranium. I made some tests in the handler code and wired up the interface and have a functional way to provide this function. I'll make some time this weekend to put together an example of my idea for @enisn review.

**Comment by BinaryAssault** [comment]
Questions:

1. Should SelectedText be cleared when the form is cleared?
2. Should SelectedText be cleared when search is empty (as in, user pressed backspace to remove all characters).

**Comment by enisn** [comment]
> 1. Should SelectedText be cleared when the form is cleared?

It should be decided in ViewModel by the end developer. If developers set's null `SelectedText` or `Text` from ViewModel, it should be cleared.

> 2. Should SelectedText be cleared when search is empty (as in, user pressed backspace to remove all characters).

That might be helpful. We can implement this scenario :)

**Comment by BinaryAssault** [comment]
@enisn, looks like you started working on AutoCompleteViewSourceOnSelected for Apple but it's currently commented out. I do not have an apple device to test on, so I only implemented the Android side. Can you look at [this commit](https://github.com/enisn/UraniumUI/commit/99a9a35cf02574d75fc9f69e8fc972f992200181) before I do a pull request? Since you don't want to clear SelectedText when a user presses clear, I added a simple local field to handle this so SelectedText persist on clear, but clears when the user removes their query. If you're ok with it I'll do a pull request.

**Comment by enisn** [comment]
Thanks for your effort. I clearly understand the logic that you started implementing. You can send the changes as a Pull Request and I'll implement iOS & MacOS platforms
