### ISSUE TITLE
[Enhancement] Allow to Programmatically Validate A FormView

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#221]
I'm using a FormView inside of a popup. I have a fairly standard layout as depicted below. Because of the separation of the InputForm from the submit button (save in this case), I cannot trigger validation when pressing save. Looking for the best way to handle this.

````
Title
-------
<FormView SubmitCommand=SaveBtn>
       .... content ...
</FormView>
-------
[SaveBtn]  [CancelBtn]
````

**Comment by enisn** [comment]
It's possible to call `Submit()` method of FormView now and it's done with https://github.com/enisn/Xamarin.Forms.InputKit/pull/338
