### ISSUE TITLE
[Bug] MaxLengthValidation False Positive

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#223]
If a property tied to an input field is null and has a MaxLengthValidation, it will report that the value is not valid. This may be true for other validations as well

Add to a FormView xaml
``````
xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"

<material:TextField Title="Max length of 50" Text="{Binding test}">
    <validation:MaxLengthValidation MaxLength="50" />
</material:TextField>
``````

Add to code behind
``````
public InputFieldsPage()
{
    InitializeComponent();
    BindingContext = this;
}

private string _test = null;
public string test
{
    get => _test;
    set => _test = value;    
}
``````

Run validation on your FormView
<img width="247" alt="image" src="https://user-images.githubusercontent.com/19739224/213798459-03c53ed1-aaa5-4fe2-97ff-8382646e0451.png">

**Comment by BinaryAssault** [comment]
Design questions for @enisn: If RequiredValidation is not in the validations, should a null value trigger other validations to show errors?

**Comment by enisn** [comment]
Since null is not string, this condition isn't met for null values:
https://github.com/enisn/Xamarin.Forms.InputKit/blob/a74e47644976d7af7df65acc8213240ab551df09/src/InputKit.Maui/Shared/Validations/MaxLengthValidation.cs#L10
