### ISSUE TITLE
[Bug] Binding a collection with no elements to a DataGrid does not update the display when adding elements

### ISSUE THREAD

**Issue by yutorisan** [enisn/UraniumUI#225]
I'm Japanese, so my English may not be native

## source

C#: 
```csharp
public class DataGridTestVM 
{
    static Random random = new();

    private ObservableCollection<Student> items = new();

    public ICommand AddCommand => new Command(() => items.Add(new Student
    {
        Id = random.Next(1, 100),
        Name = "studentRandom",
        Age = 100,
    }));
    public ICommand ClearCommand => new Command(() => items.Clear());

    public ObservableCollection<Student> Items => items;
    public DataGridTestVM()
    {
        //items.Add(new Student { Id = 1, Name = "init", Age = 100 });
        //↑it is necessary!
    }
    public class Student
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
    }
}
```

XAML:
```xaml
<Grid ui:DynamicGrid.RowCount="2" ui:DynamicGrid.ColumnCount="2">
    <Grid.BindingContext>
        <vm:DataGridTestVM/>
    </Grid.BindingContext>

    <Button Text="Add" Command="{Binding AddCommand}" Grid.Row="0" Grid.Column="0"/>
    <Button Text="Clear" Command="{Binding ClearCommand}" Grid.Row="0" Grid.Column="1" />
    <uranium:DataGrid HorizontalOptions="Center" ItemsSource="{Binding Items}" UseAutoColumns="True" Margin="30" Grid.Row="1" Grid.ColumnSpan="2">
    </uranium:DataGrid>
</Grid>
```
sorry, `ui:DynamicGrid` is self-made class that simplifies Grid settings

## problem

on c# code, If elements are not added to the collection bound to the DataGrid before the constructor, the display will not be updated even if elements are added.
However, if even one element has been added before the constructor, it can be added even if it is cleared.

### no element

before click add button:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/60573963/215325818-f6958c58-6062-4a50-9237-79f4265b301d.png">

after click add button:
<img width="192" alt="image" src="https://user-images.githubusercontent.com/60573963/215325851-798d339e-d952-4c7c-a8fc-5340fbc9e72e.png">
(For some reason the display area of the DataGrid moves slightly to the right)

### have initial element

before click add button:
<img width="223" alt="image" src="https://user-images.githubusercontent.com/60573963/215326055-4c460b6a-24c0-4a53-99dd-e90eed98853d.png">

after click add button (2 times):
<img width="284" alt="image" src="https://user-images.githubusercontent.com/60573963/215326068-f2d18e54-d649-4387-bf11-97f0dd58035f.png">

on click clear button:
<img width="302" alt="image" src="https://user-images.githubusercontent.com/60573963/215326082-4871e6cb-4b58-46d5-819e-0a4a696de268.png">

afterwards click add button:
<img width="276" alt="image" src="https://user-images.githubusercontent.com/60573963/215326105-e57fbf41-9992-4445-8a47-e72d59841586.png">

## versions

- uranium ui ver 2.3.0 (installed on nuget)
- Visual Studio for Mac 17.4.2 (build 17)
- macOS Ventura 13.0.1
- target .NET 7.0

**Comment by BinaryAssault** [comment]
I am not able to replicate this. It works with the latest version of Uranium. You may have to create a small sample app showing the issue

The only difference from my example below and your code is that I am using `[RelayCommand]` from the community toolkit MVVM package for the ICommand and a different custom object being displayed. One other difference is that my object derives from `ObservableObject`, but that shouldn't matter since the UI is listening for changes to the list and not the objects in the list. 

![testing](https://user-images.githubusercontent.com/19739224/215357737-bac12d83-a3ad-4b13-baed-a561f3019156.gif)

**Comment by enisn** [comment]
It might be related to `UseAutoColumns="True"` property

**Comment by enisn** [comment]
It seems it's not an active bug anymore. It's not reproducible now
