### ISSUE TITLE
Toggle to view Password in TextField

### ISSUE THREAD

**Issue by YBTopaz8** [enisn/UraniumUI#226]
Hello sir!
I was wondering, maybe it would be a nice addition on textfield that allows users to view their written passwords?
A little bit like this...
![image](https://user-images.githubusercontent.com/41630728/215332753-60f65af3-6e8d-4133-9f19-b950ad6b9d8e.png)

Thanks

**Comment by teeshajain17** [comment]
Hey, If no one is working on this, please assign this to me. I'll do that.
Also, please let me know where can I find this box.
Thanks.

**Comment by StepKie** [comment]
> Hey, If no one is working on this, please assign this to me. I'll do that. Also, please let me know where can I find this box. Thanks.

I love your enthusiasm, but it is not addressed by "where can I find this box". You can not "fix" something like this in XAML (like your PR #259) , you have to write actual code.

**Comment by teeshajain17** [comment]
Alright, thanks for this. Actually I am new to this. I'll fix it by writing actual code. I'll take my time to analyze first.

**Comment by enisn** [comment]
Planned in https://github.com/enisn/UraniumUI/issues/317 milestone 2.5
