### ISSUE TITLE
Using IsReadonly="True"  on TextField has no effect

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#233]
I saw that #142 was implemented, however it does not work correctly. It works as expected for the EditorField:

 <material:TextField Title="Text" IsReadonly="True" Text="ReadOnlyTextField" />

 <material:EditorField Title="Editor" IsReadonly="True" Text="ReadOnlyEditorField" />

On a minor sidenote, if it doesn't break too many clients, I would also propose to use capitalization IsReadOnly (capitalize the "O") to match the MAUI API)

**Comment by enisn** [comment]
You're right, this problem occurs because of a typo. It'll be fixed in a patch version of v2.3
