### ISSUE TITLE
Interference of Implicit Styles defined in MaterialStyleOverride.xaml and Styles.xaml

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#241]
Depending on the order it is defined in App.xaml, certain properties of implicit styles may not be applied, which is very confusing.

Using the example from the [documentation](https://enisn-projects.io/docs/en/uranium/latest/themes/material/ColorsAndStyles),
when for example adding a FontSize globally to Label's implicit style in Styles.xaml like so:

```xaml
<Style TargetType="Label">
    <Setter Property="FontSize" Value="20" />
```

this has no effect when loading a page with a label on it. It will apply the layout with HotReload when modifying it during debugging, though (for example modifying the value from 20 -> 8 will show immediate result.
When the import order of the resource dictionary in App.xaml is changed:

```xaml
 <ResourceDictionary>
      <ResourceDictionary.MergedDictionaries>
        <ResourceDictionary Source="Resources/Styles/Colors.xaml" />
        <ResourceDictionary Source="Resources/Styles/MaterialColorOverride.xaml" />
        <!-- Order of these two items was changed -->
        <ResourceDictionary Source="Resources/Styles/MaterialStyleOverride.xaml" />
        <ResourceDictionary Source="Resources/Styles/Styles.xaml" />
      </ResourceDictionary.MergedDictionaries>
    </ResourceDictionary>
```

, the implicit style from Styles.xaml is applied correctly.
It may be necessary to utilize BasedOn or another [solution](https://stackoverflow.com/questions/39234492/how-is-it-suggested-to-inherit-from-an-implicit-style-in-xamarin-forms-xaml). As is, it is very confusing (I spent two hours figuring out what was wrong :D)

**Comment by enisn** [comment]
You're right. The following style overrides the style from your application:
https://github.com/enisn/UraniumUI/blob/1d80d4136d944cf943d90aeba67d9decc8762186/src/UraniumUI.Material/Resources/StyleResource.xaml#L22-L24

I have planned to separate styles for each control but not sure that is the best approach until now. Styling will be much better in the next versions.

_For now, you can copy and place the entire style file into your application and customize it._

By the way, sorry for the bad experience. I'll work on this and find a better way.

**Comment by enisn** [comment]
This problem is solved with the new logic:
![image](https://github.com/enisn/UraniumUI/assets/23705418/0840265e-20a1-415f-98d0-50761573a07a)
