### ISSUE TITLE
[Performance] Calls to OnPropertyChanged() are often superfluous

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#242]
Not a "bug", but possible performance impact and undesired side effects when performing non-trivial operation in the `get; set; ` calls:

All the calls to `OnPropertyChanged` for the Property backing the `BindableProperty` are superfluous; these calls are performed by the framework anyway after being connected through reflection.
This can be observed when setting a breakpoint on the property's getter.
Example (from [here](https://github.com/enisn/UraniumUI/blob/develop/src/UraniumUI.Material/Controls/EditorField.BindableProperties.cs#L16)), there are many other locations

```csharp
public partial class EditorField
{
    public string Text {
        get => (string)GetValue(TextProperty); // In current implementation, at least this getter will be invoked twice
        set => SetValue(TextProperty, value);
}

    public static readonly BindableProperty TextProperty = BindableProperty.Create(
        nameof(Text),
        typeof(string),
        typeof(EditorField),
        string.Empty,
        BindingMode.TwoWay, 
        // this attribute lambda is unnecessary
        propertyChanged: (bindable, oldValue, newValue) => (bindable as EditorField).OnPropertyChanged(nameof(Text)));
```

**Comment by StepKie** [comment]
@enisn If you'd like, I could create a PR for this if you agree with the above assessment.

**Comment by enisn** [comment]
> @enisn If you'd like, I could create a PR for this if you agree with the above assessment.

It makes sense but we have to be sure always two properties are bonding.

I agree you can send a PR that changes this logic
