### ISSUE TITLE
TreeView full row highlighting

### ISSUE THREAD

**Issue by hellqvist** [enisn/UraniumUI#245]
Hi
Is it possible to highlight the full row of a tree node when selected like in the attached image?

![image](https://user-images.githubusercontent.com/13824216/221192561-06d581e6-511b-46ab-96b3-3132f10a63fa.png)

**Comment by enisn** [comment]
For now there is no built-in feature to do that, but this project implements that logic with this way:
https://github.com/FcAYH/ImageUpdateTool/blob/0aaedef1e39dfa5f0380408c0cbc3614c09826aa/ImageUpdateTool/Pages/MainPage.xaml#L22-L45

<img width="280" alt="image" src="https://user-images.githubusercontent.com/23705418/221194838-afe5baa4-5f8b-4e7b-a733-5c51abd93ca2.png">

**Comment by hellqvist** [comment]
Ok, thanks, that gives me some ideas

**Comment by billybooth** [comment]
I know this issue is closed, but this is certainly on our wishlist for the Uranium UI TreeView i.e., support for selected vs checked nodes. Thank you for everything you have done here, @enisn, as well as finding the example project above.
