### ISSUE TITLE
Add default margin for Material InputFields

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#249]
Currently, when putting fields next to each other

```xaml
<material:TextField Title="Name" AllowClear="True" Text="{v:ValidationBinding Name}"/>
<material:TextField Title="Text" IsReadOnly="True" Text="ReadOnlyTextField" />
<material:EditorField Title="Editor" IsReadOnly="True" Text="ReadOnlyEditorField" />
...
```

without setting any layout properties, they will overlap slightly:

<img width="391" alt="image" src="https://user-images.githubusercontent.com/17760200/221878421-e83fad07-af55-4a37-9dd0-c490b678b3d6.png">

This is currently fixed by adding a small margin in implicit styles: 

```xaml
<!--  Material TextFields need a little Margin to not interfere with surrounding controls  -->
<Style ApplyToDerivedTypes="True" TargetType="material:InputField">
    <Setter Property="Margin" Value="5" />
</Style>
```

_Edit:_ Funnily enough, the above does not apply the styling to the TextField, but only to the EditorField, even though they both inherit from material:InputField?!

So actually, one would need to be explicit:

```xaml
  <!-- For some unknown reason, the style below this one is applied to all InputFields but TextField, so we need to add this one... -->
  <Style TargetType="material:TextField">
    <Setter Property="Margin" Value="5" />
  </Style>

  <Style ApplyToDerivedTypes="True" TargetType="material:InputField">
    <Setter Property="Margin" Value="5" />
  </Style>
```

I would propose to add a default margin to the control to account for the space it needs when the label moves up, so it looks nice out-of-the-box. Maybe at the [rootGrid](https://github.com/enisn/UraniumUI/blob/b76fd8092de67b570bb5832c9f5957c900009748/src/UraniumUI.Material/Controls/InputField.cs#L43)?

**Comment by enisn** [comment]
This makes sense, there can be a default margin to prevent overlapping the label with other controls.

Instead of margin for all 4 ways, only vertical margin can be applied:
```xml
<Style ApplyToDerivedTypes="True" TargetType="material:InputField">
    <Setter Property="Margin" Value="0,5" />
</Style>
```

**Comment by StepKie** [comment]
> This makes sense, there can be a default margin to prevent overlapping the label with other controls.
> 
> 
> 
> Instead of margin for all 4 ways, only vertical margin can be applied:
> 
> ```xml
> 
> <Style ApplyToDerivedTypes="True" TargetType="material:InputField">
> 
>     <Setter Property="Margin" Value="0,5" />
> 
> </Style>
> 
> ```
> 
> 
> 
> 

Good point. That being the default would be nice QoL change.

Any idea why for the strange behavior that it does not inherit to TextField (but correctly to all other derived controls)?
