### ISSUE TITLE
TabView add header HorizontalOptions

### ISSUE THREAD

**Issue by CorentinSwiss4** [enisn/UraniumUI#251]
Can you add properties to center for exemple the header , actually the tab view header is force to start position.

**Comment by enisn** [comment]
`TabHeaderItemColumnWidth` was added for this reason: 
https://github.com/enisn/UraniumUI/blob/50bd77b0f4c004c4f113bae45214576d85b19c60/src/UraniumUI.Material/Controls/TabView.BindableProperties.cs#L23-L24

So, we can close this
