### ISSUE TITLE
Fix needed for material:PickerField on Windows , where as  Android and IOS working Fine

### ISSUE THREAD

**Issue by samirgcofficial** [enisn/UraniumUI#253]
If you bind a Picker Field with this model class 
 public class BrandResponseModel
    { 
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public string Name { get; set; }

    }
    Note this is a collection of Object with Property
    My Xaml looks Like this : 
    
     <material:PickerField  ItemDisplayBinding="{Binding Name}"
        Title="Pick an option" 
        ItemsSource="{Binding MyBrandResponseModel}"/> 
        
        It shows correctly when picking the items in windows : 
        
        
![One](https://user-images.githubusercontent.com/55045516/222881381-eb3e7379-cdc1-46c4-aec3-44b5da3da10f.png)

After selection then we are getting this type of output : But Note it works perfectly on Android and iOS 

![Screenshot 2023-03-04 124745](https://user-images.githubusercontent.com/55045516/222881394-3e6f77a4-99ac-478c-ba5d-f9288ada8529.png)

**Comment by enisn** [comment]
As a workaround can you try overriding ToString method in your BrandResponseModel?

```cs
    public override string ToString()
    {
        return Name;
    }
```

**Comment by Sullivan008** [comment]
Hi @enisn 

When will the bug be fixed? The "overriding ToString()" method is works, but i don't use every ViewModel this workaround. 

Thank's your asnwer!
