### ISSUE TITLE
Allow Binding of TabItem.Title

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#254]
Allow binding the Title property of TabItem to a ViewModel property, like so:

```xaml
<material:TabItem Title="{Binding ViewModel.Title}">
```

This currently leads to an exception: _XamlC error XFC0009: No property, BindableProperty, or event found for "Title", or mismatching type between value and property._, since Title is not a BindableProperty.

This would for example be useful if the Title property changes (e.g., showing the amount of items found in the TabItem etc, like

`public override string Title => $"{Res.ContentNameLocalized} ({Items.Count()})";`

**Comment by enisn** [comment]
It is possible with custom DataTemplates but it would be helpful if it's included by default in UraniumUI.

It'll be added in v2.5 release
