### ISSUE TITLE
RowStack of TreeViewNodeHolderView should have LayoutOptions.Fill

### ISSUE THREAD

**Issue by Jef-Malfliet** [enisn/UraniumUI#256]
The current implementation doesn't have `LayoutOptions.Fill` on the `RowStack`-field. This makes it so that it isn't possible to right-align controls in the `ItemTemplate` without explicitly definining the width of the root element of the `ItemTemplate`. But this is a hacky solution when the correct `LayoutOption` on `RowStack` could solve this issue.

**Comment by enisn** [comment]
It'll be included in the next patch version of v2.3
