### ISSUE TITLE
Feature Request: Ability to bind validation message without validators

### ISSUE THREAD

**Issue by aritchie** [enisn/UraniumUI#264]
This is a fantastic control library!  

I was wondering if you would consider adding a bindable field for the valdation messages as well as having your validators.  I have a viewmodel binding validation already in place that I would like to continue using.

**Comment by enisn** [comment]
It's a highly important missing feature. It's planned to be included in v2.4. Thanks for your contribution 🎉

**Comment by aritchie** [comment]
Awesome.  Thanks so much for the library & the quick turnaround!

Off topic question, but I have a community template that includes a lot of OSS libraries (that I recommend) and pre-configure for users here: https://github.com/shinyorg/templates

I'm wondering if you would be open to me adding your Uranium UI to this template?

**Comment by enisn** [comment]
Yes of course, this project has [Apache-2.0 license](https://github.com/enisn/UraniumUI/blob/develop/LICENSE) and it doesn't block you to use it as you wish. But thanks you for asking. It's ok to use in your community templates. 

---

Also, this repository has some templates in the following folder:
https://github.com/enisn/UraniumUI/tree/develop/templates
blank-app template might be helpful to see the minimum requirements for a new project.

**Comment by enisn** [comment]
https://github.com/enisn/UraniumUI/releases/tag/v2.4.0-pre.2
