### ISSUE TITLE
TreeView. The tree node content (ItemTemplate) doesn't fit the screen

### ISSUE THREAD

**Issue by Dales-Kas** [enisn/UraniumUI#269]
Tree node content doesn't fit the screen, when use layouts with HorizontalOptions="FillAndExpand" (Grid, HorizontalStacklayout, etc))

**Comment by enisn** [comment]
It was fixed by https://github.com/enisn/UraniumUI/pull/266

But it seems it's not been released yet.

**Comment by enisn** [comment]
The version has been released: 
https://github.com/enisn/UraniumUI/releases/tag/v2.3.2
