### ISSUE TITLE
Confused about colours.

### ISSUE THREAD

**Issue by MarkLFT** [enisn/UraniumUI#271]
I am a noobie to UraniumUI but love how simple it makes styling.  I have a question, I am confused about colours.  I was expecting the controls to be using the Material colours (purples), but I seem to be getting green colours?

In my MauProgram I have UseUraniumUI and UseUraniumUIMaterial, and in my app.xml I have 

'''
<ResourceDictionary.MergedDictionaries>
	<ResourceDictionary Source="Resources/Styles/Colors.xaml" />
        <material:ColorResource />
	<ResourceDictionary Source="Resources/Styles/Styles.xaml" />
        <material:StyleResource />
</ResourceDictionary.MergedDictionaries>
'''

And my color.xml in the styles folder is empty, all original colours commented out.

What am I missing to start using the Material styling (styles and colours)?

Thanks

**Comment by enisn** [comment]
Yeah, we are aware of the restrictive usage of styles. (see #241)

I'm currently working on a feature that makes style customization much easier for v2.4, but unfortunately, the only solution in the current version is replacing entire style files in your project:

https://enisn-projects.io/docs/en/uranium/latest/themes/material/ColorsAndStyles#replacing-resources

**Comment by MarkLFT** [comment]
ok, understand.  Happy to hear it's not my fault this time. ;-)  

Will have a play and override the colours until a solution is released.

Thanks

**Comment by enisn** [comment]
You can try the new approach after #272 

https://enisn-projects.io/docs/en/uranium/2.4/themes/material/ColorsAndStyles#merging-resources

It's much more flexible after `v2.4.0-pre.2`
