### ISSUE TITLE
The initial border color of TextField

### ISSUE THREAD

**Issue by pikausp** [enisn/UraniumUI#274]
After plugging Uranium into my project I noticed a weird behavior related to the border of `TextField`. It simply wasn't rendering (or it was transparent). After focusing the field the border appears with the `AccentColor` and once the focus is lost the border stays, but switches to the basic border color.

I spent quite a while on this unable to figure out the culprit. What I did to reproduce this behavior was create a new project from the app template and I located the following in the Styles.xaml

```
<Style TargetType="Border">
    <Setter Property="Stroke" Value="{AppThemeBinding Light={StaticResource Gray200}, Dark={StaticResource Gray500}}" />
    <Setter Property="StrokeShape" Value="Rectangle"/>
    <Setter Property="StrokeThickness" Value="1"/>
</Style>
```

Apparently, this is what gives the border its color in the beginning. When I changed the value to a random color the `TextField` ended up having 3 border colors.

1) The border color set by the global border style above, which would be the default border color prior to the field ever receiving focus
2) The accent color which would be applied when the field has focus
3) The regular border color which is applied when the field loses focus (but it must have obtained focus before, otherwise the color from the global style is applied

What is the guidance here? I don't think it should be required to define global border styles for the `TextField` to function as a component. Given that this happens in the template as well, is it safe to assume this is a bug?

**Comment by enisn** [comment]
Hi @pikausp 

This is a known issue and was solved by #272 and shipped in `v2.4.0-pre.2`.

MAUI Style system works on Key-Value logic and when a another resource is added with the same key, it overrides the previous one. I couldn't overcome this issue and I made #272  feature. So you can override or use your existing styles as base styles for UraniumUI styles.

You can see the updated documentation for v2.4
https://github.com/enisn/UraniumUI/blob/rel-2.4/docs/en/themes/material/ColorsAndStyles.md

So you can define which style will be applied at the end state of the application.

---

InputFields use the MAUI Border to render their borders and global Border style will automatically applied to their borders. We'll assign a unique style class for inputfield borders and we'll prevent applying global border styles to InputFields

**Comment by enisn** [comment]
Planned and will be overhauled in v2.5

**Comment by enisn** [comment]
now it's possible to override border color like below:

App.xaml:
```xml
<m:StyleResource>
    <m:StyleResource.Overrides>
        <ResourceDictionary>
            <Style TargetType="m:TextField" ApplyToDerivedTypes="True" CanCascade="True">
                <Setter Property="BorderColor" Value="Blue" />
            </Style>
        </ResourceDictionary>
    </m:StyleResource.Overrides>
</m:StyleResource>
```

and see the result:

![uraniumui-windows-border-fix](https://github.com/enisn/UraniumUI/assets/23705418/6f5c6d4a-18aa-493e-b0cc-a0ddc1663597)
