### ISSUE TITLE
Word wrapping for RadioButton and CheckBox

### ISSUE THREAD

**Issue by pikausp** [enisn/UraniumUI#276]
When the text exceeds the screen width it gets clipped instead of being wrapped. I wasn't able to get it working.
![image](https://user-images.githubusercontent.com/6717146/231141542-9f96d7a1-bba7-4a49-9148-5939a73b8075.png)

When I was browsing the code in `InputKit` I found this [remark](https://github.com/enisn/Xamarin.Forms.InputKit/blob/2e6a4edd38f6827a0297bfec3f35257b98fece75/src/InputKit.Maui/Shared/Controls/CheckBox.cs#L362) which suggests there is a workaround needed but the text should wrap. Is that not the case? Am I doing something incorrectly?

Secondly, this [comment](https://github.com/dotnet/maui/issues/12415#issuecomment-1377754530) proposes to use a two-column `Grid` to achieve the appropriate wrapping behavior. Reading the linked issue suggests that the `HorizontalStackLayout` behavior is desired and it won't be changed.

I'm using the controls from the `Uranium.Material` package so I posted in this repo instead of the `InputKit` one.

**Comment by enisn** [comment]
Yeah, It's an MAUI Stacklayout issue and the issue (https://github.com/dotnet/maui/issues/8873#issuecomment-1287768160) is still open.

I'll try to overcome this issue according to this [comment](https://github.com/dotnet/maui/issues/12415#issuecomment-1377754530)

**Comment by pikausp** [comment]
I tested the `Grid` solution and it seems to work without a problem. Do you have an idea about the vertical position of the `CheckBox`/`RadioButton` when text wrapping occurs? I could see an argument for both `Center` and `Start` (`End` not so much)

**Comment by pikausp** [comment]
@enisn do you have any idea when you might be able to get to it? I'm more than happy to help with the implementation (the feature is quite important). Just given that the whole controls inherit from StatefulStackLayout I'm not sure about the approach you want to take.

**Comment by enisn** [comment]
This issue should be fixed with a workaround with `v2.3.3` release.

I'll refactor completely CheckBox in further feature releases

**Comment by pikausp** [comment]
There is still an issue with the width of the `Label`. I submitted an issue in the other repo with a PR proposal that would fix the issue and add further enhancements. So whenever you have time we can continue there :)

**Comment by pikausp** [comment]
@enisn would you have a second to take a look at https://github.com/enisn/Xamarin.Forms.InputKit/issues/348?

**Comment by enisn** [comment]
Closed by https://github.com/enisn/Xamarin.Forms.InputKit/pull/350

It'll be released in the next patch release of UraniumUI 2.4


Thanks @pikausp 🎉
