### ISSUE TITLE
Controls not clickable on macOS with 2.4.2

### ISSUE THREAD

**Issue by sandreas** [enisn/UraniumUI#296]
Hey,

I would like to test the awesome `UraniumUI` kit, but unfortunately, I cannot get it to work on macOS, because the controls are not `clickable` (or cannot be focussed).

Maybe I'm doing something wrong, but I followed the documentation as close as possible...

Binding works, but I cannot edit or focus the TextField... What am I doing wrong?

Example Page:

```xaml
<?xml version="1.0" encoding="utf-8"?>
<uranium:UraniumContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
                            xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
                            xmlns:viewModels="clr-namespace:MyApp.Maui.ViewModels"
                            xmlns:uranium="http://schemas.enisn-projects.io/dotnet/maui/uraniumui"
                            xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui"
                            xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
                            xmlns:input="clr-namespace:InputKit.Shared.Controls;assembly=InputKit.Maui"
                            x:Class="MyApp.Maui.Views.SettingsPage"
                            x:DataType="viewModels:SettingsViewModel"
                            Title="{Binding Title}"
                            Shell.NavBarIsVisible="{Binding NavBarIsVisible}">
    <uranium:UraniumContentPage.Content>
        <Grid RowDefinitions="*" ColumnDefinitions="*" Padding="50">
            <input:FormView>
                <material:TextField Title="Url" Text="{Binding Url}">
                    <validation:RequiredValidation />
                </material:TextField>
            </input:FormView>
        </Grid>
    </uranium:UraniumContentPage.Content>
</uranium:UraniumContentPage>
```

**Comment by enisn** [comment]
Might be related to #281

**Comment by sandreas** [comment]
> Might be related to https://github.com/enisn/UraniumUI/issues/281

Maybe... thank you for keeping this issue up to date.

I'm really sorry, I had to ditch UraniumUI because I needed something that is working RIGHT NOW. Maybe I'll give this a try in the next release of my app, but this issue was a K.O. 

I'll report back, if the workaround you suggested is working, but this may take a while.

**Comment by enisn** [comment]
2.4.3 was released, I've checked on my Mac and it seems working right now:
![7f8cad563e7e3f](https://user-images.githubusercontent.com/23705418/236664517-339bd4b0-fbaa-44e9-ac50-54568229db04.gif)

**Comment by sandreas** [comment]
Cool I'll give it a spin in the next days.

Thank you for the great support 😊

**Comment by enisn** [comment]
Closing this issue, feel free to reopen if you reproduce the problem
