### ISSUE TITLE
Error when running after installation on an existing project

### ISSUE THREAD

**Issue by dlwhdvlf71** [enisn/UraniumUI#297]
Hello. I tried to install and use the Uranium UI that you provide in an existing project, but there was a problem.

I did it in the way it appeared on the Getting Started page, but when I run the debug, I get the error phrase 'Microsoft.Maui.Controls.Xaml.Xaml.XamlParseException: 'Position 14:41. Can not find the object reference by appStyles'?

[App.xaml]
<Application.Resources>
<ResourceDictionary>
<ResourceDictionary.MergedDictionaries>
<ResourceDictionary Source="Resources/Styles/Colors.xaml" />
<material:ColorResource />
<ResourceDictionary Source="Resources/Styles/Styles.xaml" />
<material:StyleResource BasedOn="{x:Reference appStyles}" />

</ResourceDictionary.MergedDictionaries>
</ResourceDictionary>
</Application.Resources>

**Comment by enisn** [comment]
If you don't use your own styles as base of uranium styles, you can just remove `BasedOn="{x:Reference appStyles}"` part

**Comment by dlwhdvlf71** [comment]
I remove it as I told you, so it debugs normally.
By the way, if I click the header in Data Grid, is there a function that aligns based on the header?
