### ISSUE TITLE
TreeView ItemTemplate - Property "Name" not found

### ISSUE THREAD

**Issue by C00lzer0** [enisn/UraniumUI#302]
Hi there, 
i've played around with your UI Framework (awesome work by the way), espacilly with the TreeView. 
As of your documentation (https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/TreeView) i tried the TreeView with ItemTemplate but VS always said that the "Name" property could not be found in the DataContext :o(.

This is the Binding used directly from the documentation:
`[...] <Label Text="{Binding Name}" FontAttributes="Bold" /> [...]`

And the error from VS:
XFC0045 Binding: Property "Name" not found on "Maui_VijayAnand_Net7_UraniumUI.ViewModels.UraniumUITreeViewViewModel".	Maui_VijayAnand_Net7_UraniumUI

Can you confirm or did i miss something here?

I am using:
> Microsoft Visual Studio Professional 2022
> Version 17.5.5
> VisualStudio.17.Release/17.5.5+33627.172
> Microsoft .NET Framework
> Version 4.8.09032

Project settings:
> .NET 7
> UraniumUI 2.4.2
> .NET MAUI Project and Item Templates Extension 
(https://marketplace.visualstudio.com/items?itemName=egvijayanand.maui-templates)
> - The template settings i have used could be found in the "Used_Template_Config.png" inside the project.

Here is the whole test project:
[Maui_VijayAnand_Net7_UraniumUI.zip](https://github.com/enisn/UraniumUI/files/11412330/Maui_VijayAnand_Net7_UraniumUI.zip)

**Comment by enisn** [comment]
It seems your project uses [Compiled Bindings](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/data-binding/compiled-bindings), so you should set `x:DataType` for your `DataTemplate`.


**TreeNode** class is placed under Models folder, so add the following xml namesapce to your page:

```
xmlns:models="clr-namespace:Maui_VijayAnand_Net7_UraniumUI.Models"
```

Then add DataType to your DataTemplate

```xml
<material:TreeView ItemsSource="{Binding TreeItems}">
    <material:TreeView.ItemTemplate>
         <!--         Check here 👇 -->
        <DataTemplate x:DataType="models:TreeNode">
            <HorizontalStackLayout Spacing="5">
                <Image Source="{FontImageSource FontFamily=FASolid, Glyph={x:Static fa:Regular.Folder}, Color={StaticResource Primary}}" />
                <Label Text="{Binding Name}" FontAttributes="Bold" />
                <!--<Label Text="{Binding Children.Count, StringFormat='({0})'}" />-->
            </HorizontalStackLayout>
        </DataTemplate>
    </material:TreeView.ItemTemplate>
</material:TreeView>
```

Then your TreeView is rendered:
![image](https://user-images.githubusercontent.com/23705418/236633710-5448e23b-b753-4c70-b184-5a7e4310273a.png)

**Comment by C00lzer0** [comment]
It works now ... thank you for pointing me in the right direction.
I read about Compiled Bindings some weeks ago but realy could not think of it at this moment (shame on me).

The next step now is to figure out how to make the nodes selectable :o).

Happy Weekend
