### ISSUE TITLE
Commands should have event equivalents

### ISSUE THREAD

**Issue by daltzctr** [enisn/UraniumUI#309]
Any control that has a command, should have an equivalent event. The reasoning behind this is a good application architecture will keep all GUI <-> GUI modifying code in the XAML code-behind. 

An example of this is implementing a `ButtonView` that changes layout of a child element of the current page. It is bad practice to leak your UI element into the `ViewModel`, so this behavior is best done with an event. However, `ButtonView` does not have a `Tapped`, `Pressed` or other similar event.

Workaround: `TapGestureRecognizer`

**Comment by enisn** [comment]
ButtonView has only Commands such as `PressedCommand`, `HoverCommand`, `HoverExitCommand`, `LongPressCommand` and `TappedCommand`.

But it seems there are no events equivalent to those commands. It's planned and will be added in the next 2.5 milestone.

---

You can set Commands as a workaround.

```xml
<material:ButtonView x:Name="myButton">
    <Label Text"MyButtonText"  />
</material:ButtonView>
```

```csharp
myButton.TappedCommand = new Command(()=>
{
    Console.WriteLine("Hello, button tapped!");
});
```

**Comment by daltzctr** [comment]
Excellent workaround. Thanks.
