### ISSUE TITLE
`ButtonView` is missing CornerRadius and BorderColor

### ISSUE THREAD

**Issue by daltzctr** [enisn/UraniumUI#310]
`ButtonView` should probably just inherit the controls from `Button`, but I'm not sure how it works under the hood.

**Comment by enisn** [comment]
ButtonView has a [Border](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/controls/border) around the content.

Something like `StrokeShape="RoundRectangle 20"` can solve the problem

**Comment by daltzctr** [comment]
I'm not sure I understand, would you be able to provide a XAML example of modifying the `ButtonView` `CornerRadius` and `BorderColor`?

**Comment by enisn** [comment]
You can set a radius for specific corner like below:
```xml
<material:ButtonView StrokeShape="RoundRectangle 20,10,5,0" StrokeThickness="4" Stroke="Red" >
    <Label Text=" Hello, World!" HorizontalOptions="Center" />
</material:ButtonView>
```

![image](https://github.com/enisn/UraniumUI/assets/23705418/cb5a70b6-7e52-44e4-a3dc-f5b66bb02176)
