### ISSUE TITLE
Bottom Sheet as a Control?!

### ISSUE THREAD

**Issue by Sullivan008** [enisn/UraniumUI#329]
Hi @enisn ,

I saw your Bottom Sheet - Documentation in your project website, and I want to try it. I saw that the control can only be used if I implement it in a Page. 

I built the application in such a way that I use 1 Page and change the Content View (Presenter) during navigation, like a One Side Page - Application. But in this way I cannot use the Bottom Sheet Feature, because I have just Content views.

Is it possible that the Bottom Sheet is not linked to the Page, but to the Content View?

Thank's for your answer!

**Comment by enisn** [comment]
As cross-platform concerns, it's a simple view that is attached to UraniumContentPage. UraniumUI aims to support all the platforms and desktops don't have any bottom sheet, so this is a common solution in UraniumUI. 

If you're developing a mobile app (Andro,d/iOS), you can use third party libraries such as [The49.Maui.BottomSheet](https://github.com/the49code/The49.Maui.BottomSheet). This library provides a native bottom sheet.

**Comment by enisn** [comment]
By the way, I'm planning to add adapter libraries in UraniumUI for third party bottom sheet implementations like [UraniumUI.Dialogs](https://enisn-projects.io/docs/en/uranium/latest/dialogs/Index). But for now, bottomsheet implementation is just simple.
