### ISSUE TITLE
Please fix - EditorField - Not Auto Resize - Windows and Android.

### ISSUE THREAD

**Issue by Sullivan008** [enisn/UraniumUI#330]
Hi @enisn 

The EditorField does not auto resize when i wrote a long text.

---
It's my example: 

![not_auto_resize](https://github.com/enisn/UraniumUI/assets/47091541/453a9ddb-8902-42c6-805a-4c85a93ee3b2)

---
It's yout example on project website: 

![your_example](https://github.com/enisn/UraniumUI/assets/47091541/46cd7f77-33ed-4a2a-a481-941c4aecdf65)

---
My Code: 

`<material:EditorField 
        Title="Name"
        Text="{Binding Name}"/>`

**Comment by enisn** [comment]
Which platform are you working?

There is a known issue on windows, you can set HeightRequest on windows

**Comment by Sullivan008** [comment]
I working on - Android and Windows. but it doesn't work on android either (I tried on project - sample project)

Do I need to set a fix HeighRequest? Does not work on automatically?

**Comment by enisn** [comment]
Happens after https://github.com/enisn/UraniumUI/pull/294
