### ISSUE TITLE
ButtonView tapped trigger

### ISSUE THREAD

**Issue by pikausp** [enisn/UraniumUI#353]
I use ButtonView within a CollectionView to allow users to navigate to the detail of the item they clicked. However, when the user wants to scroll the `TappedCommand` gets executed. This does not happen if I use the native `TapGestureRecognizer` on a `Grid` for example. The tap is recognized correctly.

Is this intended behavior or is it a bug?

**Comment by enisn** [comment]
It's not an expected behavior. On which platform do you face this issue?

**Comment by pikausp** [comment]
Android 33, both emulator and physical devices. I just notice it doesn't happen every time and at some places within the application, it works as expected. Going to investigate further and add more details.

**Comment by pikausp** [comment]
https://github.com/pikausp/ButtonViewScrollRepro this demonstrates the issue

**Comment by enisn** [comment]
Thanks for you demo, I found it.

The following line causes the problem:
https://github.com/enisn/UraniumUI/blob/b31b3d2cb20d10da9e0653c97ae5ddef06647713/src/UraniumUI.Material/Handlers/ButtonViewHandler.Android.cs#L54

It invokes tepped command even event is cancelled.
