### ISSUE TITLE
TextField does not work in 2.4.6 version. - Windows and Android

### ISSUE THREAD

**Issue by Sullivan008** [enisn/UraniumUI#354]
Hi @enisn,

The TextField input does not working in 2.4.6 version. When I click the input field the cursor does not appearing and i cant write anithing in this field.

Is the error not caused by the patch #339 that you made for Bug #330?

Environment: Windows and Android
VS Version Number: 17.5.5

**Comment by enisn** [comment]
Yes you're completely right, it happended after #339 and we upgraded to MAUI 7.0.86

If you still use 7.0.81 version, you may face the exactly same issue like previous.

Try updating your MAUI workloads:
```bash
dotnet workload update
```
_--or for first time installation --_
```bash
dotnet workload install maui
```

- If you have multiple versions installed, try set `<MauiVersion>` tag in your.csproj file:
```xml
   <PropertyGroup>
        <MauiVersion>7.0.86</MauiVersion>
    </PropertyGroup>
```
