### ISSUE TITLE
TextField has a large minimum height

### ISSUE THREAD

**Issue by daltzctr** [enisn/UraniumUI#370]
TextField seems to have a forced MinimumHeight of around ~40-50px. This makes developing regular desktop layouts (which standardize on ~30px height for text entries) somewhat painful.

**Comment by enisn** [comment]
We just removed HeightRequest from InputFields with PR https://github.com/enisn/UraniumUI/pull/339

You should be able to customize height of controls. 

Try decreasing font sizes and try setting lesser HwightRequest for **Entry**

Something like below. I didn't tried the values, you can find best values for your requirement.

```xml
<material:TextField Title="Something">
  <material:TextField.Resources>
    <ResourceDictionary>
      <Style TargetType="Entry" ApplyToDerivedTypes="True">
          <Setter Property="FontSize" Value="11" />
          <Setter Property="HeightRequest" Value="20" />
      </Style>
    </ResourceDictionary>
  </material:TextField.Resources>
<material:TextField>
```

> You can define a global style for your application instead setting for each Textfield one by one.

**Comment by daltzctr** [comment]
Hm. It might be default padding in the control...

**Comment by enisn** [comment]
It can't be reproduces at the latest MAUI & UUI version.

Feel free to reopen this issue with reproduction steps if problem continues
