### ISSUE TITLE
TextField Text already entered will not be displayed

### ISSUE THREAD

**Issue by DimplesHei** [enisn/UraniumUI#380]
![notdis](https://github.com/enisn/UraniumUI/assets/11221064/9b4cb11d-ef39-4c34-91c1-dcb1771f8daf)

**Comment by enisn** [comment]
Can provide which version are you using and which problem the problem occurred on?

**Comment by enisn** [comment]
Also make sure the text isn't white on a white background

**Comment by DimplesHei** [comment]
version:  UraniumUI.Material  2.5.0
text color is black

**Comment by DimplesHei** [comment]
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="GrandUnified.MauiFront.Pages.LoginPage" 
             xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"  
             xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
             xmlns:validation="clr-namespace:InputKit.Shared.Validations;assembly=InputKit.Maui" 
             xmlns:input="clr-namespace:InputKit.Shared.Controls;assembly=InputKit.Maui"
             xmlns:materialIcons="clr-namespace:UraniumUI.Icons.MaterialIcons;assembly=UraniumUI.Icons.MaterialIcons"
             xmlns:viewmodels="clr-namespace:GrandUnified.MauiFront.ViewModels" 
             x:DataType="viewmodels:LoginViewModel"
             Title="Login" >
    <Shell.NavBarIsVisible>False</Shell.NavBarIsVisible>
    <ContentPage.Content>
     <ScrollView>  
            <StackLayout Orientation="Vertical" BackgroundColor="{Binding Background.Color}">
                <Image Aspect="AspectFill" Source="login_banner" HeightRequest="200" Margin="0,0,0,60"></Image> 
                <input:FormView x:Name="inputForm" Spacing="20" Margin="20,0,20,0" SubmitCommand="{Binding LoginCommand}" >
                    <material:TextField CornerRadius="0" BorderColor="{Binding Foreground.Color}"  TitleColor="{Binding Foreground.Color}" TextColor="{Binding Foreground.Color}"  x:Name="txtUserName"  IsEnabled="{Binding Enabled}" Text="{Binding UserName}" Title="UserName" Icon="{FontImageSource FontFamily=MaterialOutlined, Color={ Binding Foreground.Color}, Glyph={x:Static materialIcons:MaterialOutlined.Person}}" AllowClear="True">
                        <validation:RequiredValidation  Message="UserName" />
                    </material:TextField>

                    <material:TextField CornerRadius="0"  x:Name="txtPassword"  BorderColor="{Binding Foreground.Color}" TitleColor="{Binding Foreground.Color}"   TextColor="{Binding Foreground.Color}"    IsEnabled="{Binding Enabled}"  Text="{Binding Password }"  Title="Password"   IsPassword="True"  Icon="{FontImageSource FontFamily=MaterialOutlined, Color={Binding Foreground.Color}, Glyph={x:Static materialIcons:MaterialOutlined.Lock}}" AllowClear="True" >
                        <material:TextField.Validations>
                            <validation:RequiredValidation Message="Password Not Allow Empty" />
                            <validation:MinLengthValidation MinLength="6"  Message="Password Length Must Greater than 6"  />
                        </material:TextField.Validations >
                        <material:TextField.Attachments>
                            <material:TextFieldPasswordShowHideAttachment />
                        </material:TextField.Attachments> 
                    </material:TextField>

                    <Button  x:Name="btnLogin"  Text="Login"  IsEnabled="{Binding Enabled}" TextColor="White" BackgroundColor="{Binding ThemeColor }" input:FormView.IsSubmitButton="True" HeightRequest="50" /> 
                    
                </input:FormView>
                <Frame HasShadow="True"  BorderColor="Transparent" BackgroundColor="White" IsVisible="{Binding ProgressViewModel.ProgressVisible}"  VerticalOptions="Center" CornerRadius="48" HorizontalOptions="Center" WidthRequest="48" HeightRequest="48" Padding="5">
                    <Grid >
                        <ActivityIndicator BackgroundColor="Transparent" Color="{Binding ProgressViewModel.ThemeColor}" IsRunning="True" VerticalOptions="Center" HorizontalOptions="Center" HeightRequest="36" WidthRequest="36"   />
                        <Label BackgroundColor="White" x:Name="lblCurProgress"   Text="{Binding ProgressViewModel.ProgressTip}" Grid.Row="0" VerticalOptions="Center" HorizontalOptions="Center"  />
                    </Grid>
                </Frame>
               
            </StackLayout> 
        </ScrollView>
    </ContentPage.Content>
</ContentPage>

**Comment by DimplesHei** [comment]
> Also make sure the text isn't white on a white background

text color is black,   background is white.

**Comment by enisn** [comment]
Related to https://github.com/enisn/UraniumUI/issues/281

And it should be solved with the related issue.

Feel free to re-open if issue continues
