### ISSUE TITLE
BUG - BottomView blocks content

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#385]
This may be more of a MAUI issue, but I have an editor box at the end of a screen that is blocked partially by the BottomView. The editor is inside a ScrollView with various other UI TextFields. In the image below, you can see the very last UI EditorField is cut off by the BottomView, and I cannot scroll any further

<img width="261" alt="image" src="https://github.com/enisn/UraniumUI/assets/19739224/89372bb8-6ebf-42e7-81fd-f4888ab9d50c">

**Comment by enisn** [comment]
The uraniumui bottom sheet rendered over the UraniumContentPage content.

So, bottomview header will be always rendered over the actual content, you can add bottom padding to your page or the main StackLayout/Grid/.. that keeps your content to overcome this, it's designed to be rendered always over the content including when it's not presented. 

```xml
<uranium:UraniumContentPage x:Class="UraniumApp.Pages.BottomSheets.RegularBottomSheetPage"
             xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             Padding="0,0,0,50"


>
```

---

Or you can remove the header of bottom page if you manage it programmatically by setting header in XAML

```xml
 <uranium:UraniumContentPage.Attachments>
     <material:BottomSheetView x:Name="bottomSheet">
         <material:BottomSheetView.Header>
             <BoxView HeightRequest="0" /> <!-- No header -->
         </material:BottomSheetView.Header>
...
```
![headerless-bottomsheet](https://github.com/enisn/UraniumUI/assets/23705418/31daf685-d1d6-4056-bf11-81a050f9cdf4)
