### ISSUE TITLE
Programmatically set the icon color in a textfield

### ISSUE THREAD

**Issue by PulaiGabor** [enisn/UraniumUI#397]
Hello!

I would like to set the icon property of a textfield in C#. But it is invisible, I think its color has to be set.
How can I set the color of the icon?

Or if it's not the color then what is it?

Thank you!

**Comment by enisn** [comment]
You can use [FontImageSource](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/fonts#display-font-icons) in C# code too.

Try the following

_XAML_
```xml
 <material:TextField Title="Hello, World!" x:Name="myTextField" />
```

_CS_
```csharp
myTextField.Icon = new FontImageSource
{
    FontFamily = "MaterialRegular",
    Glyph = MaterialRegular.Language,
    Color = Colors.Blue,
};
```

![image](https://github.com/enisn/UraniumUI/assets/23705418/975fb029-1361-48e9-bc5d-200d41a51e6c)

**Comment by PulaiGabor** [comment]
Works fine. Thank you for your fast help :)
