### ISSUE TITLE
Update to MAUI `7.0.0-rc.1.6683`

### ISSUE THREAD

**Issue by enisn** [enisn/UraniumUI#41]
https://github.com/dotnet/maui/releases/tag/7.0.0-rc.1.6683

**Comment by ghost** [comment]
Hey @enisn! Is 2.0 planned to come out with dotnet 7? There's a new release candidate (https://github.com/dotnet/maui/releases/tag/7.0.0-rc.2.6866) but didn't see an issue logged here yet.

I also tried using the TreeView (great control btw) targeting net7.0, but it throws an exception:
System.MissingMethodException: 'Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)'

**Comment by enisn** [comment]
> Hey @enisn! Is 2.0 planned to come out with dotnet 7? There's a new release candidate (https://github.com/dotnet/maui/releases/tag/7.0.0-rc.2.6866) but didn't see an issue logged here yet.
> 
> I also tried using the TreeView (great control btw) targeting net7.0, but it throws an exception: System.MissingMethodException: 'Method not found: void Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped(System.EventHandler)'

Same issue with https://github.com/enisn/UraniumUI/issues/74

Currently, there is no version released that targets .net 7

**Comment by enisn** [comment]
done in #92
