### ISSUE TITLE
Editor new line not working properly.

### ISSUE THREAD

**Issue by Petrarca181** [enisn/UraniumUI#419]
All default. 2.5.4
 
![ezgif com-crop](https://github.com/enisn/UraniumUI/assets/54235138/8dc0cd0e-394c-4713-a178-3dbcadee8303)

new line pushes editor on top.

**Comment by BinaryAssault** [comment]
Might be related: editor doesn't respect height request. If one is set, and a user presses return, the control endlessly expands as long as return is being pressed

**Comment by enisn** [comment]
Sorry, I couldn't reproduce at the latest version
![editorfield-reproduce](https://github.com/enisn/UraniumUI/assets/23705418/49e6f3c8-839c-4f3e-affe-b611f9f09d10)

Feel free to re-open this issue with reproduction steps if you reproduce it again
