### ISSUE TITLE
Website enisn-projects.io seems to be dead

### ISSUE THREAD

**Issue by chrootlogin** [enisn/UraniumUI#421]
When I try opening the project website I end up with a blank page.

Tried with multiple browsers (Safari, Firefox and Chrome) on a MacBook.

Related URL: https://enisn-projects.io/docs/en/uranium/latest/Getting-Started

**Comment by enisn** [comment]
I'll check quickly

**Comment by enisn** [comment]
Until the resolution, you can use the docs folder in this repository
https://github.com/enisn/UraniumUI/tree/develop/docs/en

**Comment by enisn** [comment]
I just roll-back to too old backup. At least it's working now
