### ISSUE TITLE
How do I change the color of "Clear icon" and "Icon Hide and show password"

### ISSUE THREAD

**Issue by Cr15Denis** [enisn/UraniumUI#429]
![Screenshot_1691942452](https://github.com/enisn/UraniumUI/assets/70722700/316e12d7-96c3-48f0-bad4-c605cefc6c42)

<material:TextField Title="Password" IsPassword="True"  AccentColor="Black" Icon="{FontImageSource FontFamily=MaterialRegular, Glyph={x:Static m:MaterialRegular.Password}}" >
    <material:TextField.Attachments>
        <material:TextFieldPasswordShowHideAttachment  />
    </material:TextField.Attachments>
</material:TextField>

**Comment by enisn** [comment]
Currently, they don't have any specific property to change .

But they use `OnBackground` and `OnBackgroundDark` colors from the resource dictionary. 

You can [Override Colors](https://enisn-projects.io/docs/en/uranium/latest/themes/material/ColorsAndStyles#changing-colors) of UraniumUI and define `OnBackground` color in your `Colors.xaml` file. But this color will change entire objects color thar rendered on `BackgroundColor`.
```xml
    <Color x:Key="OnBackground">#YOUR_COLOR</Color>
    <Color x:Key="OnBackgroundDark">#YOUR_COLOR_ON_DARK</Color>
```


I'll add properties to change those colors from XAML pages.


---
