### ISSUE TITLE
XamlParseException setting BorderThickness

### ISSUE THREAD

**Issue by robgrav** [enisn/UraniumUI#435]
With the TextField control, setting the BorderThickness property in XAML results in a XamlParseException.

Looks like it's related to the recently added BorderThicknessProperty in InputField. 
InputBackgroundColorProperty and InputBackgroundProperty have the same issue.

BorderThicknessProperty: nameof(BorderColor) should be nameof(BorderThickness)
InputBackgroundColorProperty: nameof(BorderColor) should be nameof(InputBackgroundColor)
InputBackgroundProperty: nameof(BorderColor) should be nameof(InputBackground)

https://github.com/enisn/UraniumUI/commit/43633bc623c6fd677da3fcf0b67f5b5d6ea1397e

**Comment by enisn** [comment]
Probably fixed by https://github.com/enisn/UraniumUI/pull/467
