### ISSUE TITLE
Updating UraniumUI.Icons.MaterialIcons to 2.5.5 crashes app in android release mode

### ISSUE THREAD

**Issue by ketakidevendra** [enisn/UraniumUI#444]
I did update from UraniumUI.Icons.MaterialIcons to 2.5.0 to UraniumUI.Icons.MaterialIcons to 2.5.5 
My app started crashing on app start only in release mode in android.
With version 2.5.0 it works without crashing all versions after 2.5.0 are crashing in release mode in android.

![image](https://github.com/enisn/UraniumUI/assets/53600181/107251be-b4d8-44f8-801c-8948c951a732)

**Comment by enisn** [comment]
Do you have any logs of crash dump related to that?

By the way, do you use only this package? If you use other UraniumUI packages too, you should upgrade all of them at the same time

**Comment by ketakidevendra** [comment]
Yes I did update all Uranium packages. I observed issue only after upgrading this package. Downgrade only Material Icons to 2.5.0 and keeping all other at 2.5.5 works well.
Attached is logcat from VS 2022
![image](https://github.com/enisn/UraniumUI/assets/53600181/8bd6582f-f9a8-4724-9106-7eaff502c8ff)
[Logcat.txt](https://github.com/enisn/UraniumUI/files/12671797/Logcat.txt)

**Comment by StepKie** [comment]
@enisn from the log file:

GUID of dependent assembly UraniumUI.Icons.MaterialIcons doesn't match (expected 'D817532D-A41A-43EE-A01B-376B40D3E1F4', got '77FE557B-A206-41C0-9B1E-79C48017BD88')

**Comment by enisn** [comment]
I haven't changed project GUID but there might be a problem with Nuget packing. 

Can you try again after clearing nuget cache?
```bash
dotnet nuget locals all --clear
```

**Comment by ketakidevendra** [comment]
Closing this issue as it is no more reproducible after upgrading to latest version.
