### ISSUE TITLE
[Bug] Does the iOS version in release work?

### ISSUE THREAD

**Issue by roswer13** [enisn/UraniumUI#448]
For UraniumUI.Material with iOS version 4.5.5 in release, when loading the page the application crashes.
Minimum Target iOS Framework: 14.2

MauiProgram.cs
```c#
 builder.UseUraniumUI()
        .UseUraniumUIMaterial()
``` 
Page.xaml
```xaml
<ContentPage.Content>
    <ScrollView>
        <VerticalStackLayout Margin="24" Spacing="12">

            <Label Text="Entries" />

            <material:TextField Title="Por defecto" />

        </VerticalStackLayout>
    </ScrollView>
</ContentPage.Content>
```

**Comment by enisn** [comment]
Is there any crash report?
You can use AppCenter or equivalent tools to collect crash reports from devices in production environment

**Comment by roswer13** [comment]
Sure.
I have this.

![image](https://github.com/enisn/UraniumUI/assets/22887165/743aff69-b23f-4afe-8388-955ab0896655)

Best regards.

**Comment by enisn** [comment]
Ok thanks, it really helps, I'll work on it
