### ISSUE TITLE
Adding a simple border on any UraniumContentPage will break the whole page and show blank (tested on android for now)

### ISSUE THREAD

**Issue by YBTopaz8** [enisn/UraniumUI#481]
So With .net 8 out, I updated my project, and i realized that Borders won't work on any uranium contentpage or bottomsheet (as far as i have tested). no matter the complexity.
Steps to reproduce
1. create a sample app
2. add a blank UraniumContentPage
3. add a simple border `<Border> <label text="test"/> </border>`
4. run on android emulator
5. navigate to uranium page. it will blank
6. remove borders and leave texts only. re-run
7. it will show text normally

Video for demo
i'm on v2.5.6

https://github.com/enisn/UraniumUI/assets/41630728/7867c9ad-2982-4a05-a6dc-62da69bd8ba0

**Comment by YBTopaz8** [comment]
Tested with latest pre-release version and still same issue

**Comment by YBTopaz8** [comment]
By the way it works just well on CommunityToolkit Popups. I (was suprised to) realize that today 😄 . Just to let you know if it helps


https://github.com/enisn/UraniumUI/assets/41630728/d1c1f77c-efc8-4288-a10c-6a9508a6e783

**Comment by YBTopaz8** [comment]
One Workaround for now is using Frame.
Frame works perfectly well 
(sorry for commenting too much 😅)

**Comment by enisn** [comment]
> One Workaround for now is using Frame. Frame works perfectly well (sorry for commenting too much 😅)

It's strange behavior, there is no reason that I found so far.

 Probably I'm going to release v2.6 without this major bug fix for .NET 8 compatibility and fix it in later in v2.6.1

**Comment by DanielSCBO** [comment]
The uranium contente page use any frame inside? If use the problem maybe related to 

https://github.com/dotnet/maui/issues/18526

**Comment by enisn** [comment]
> The uranium contente page use any frame inside? If use the problem maybe related to
> 
> [dotnet/maui#18526](https://github.com/dotnet/maui/issues/18526)

Thanks for the information, probably it causes the problem 👍

**Comment by enisn** [comment]
I applied a workaround with #496 

By the way, `Border` seems more lightweight than Frame, It's a persistent change instead a temporary workaround. 

This change might change existing designs, so I'll release another major version as `v2.7`,

Unfortunately, v2.6 has become only for .net8 support, new features will come with v2.7

**Comment by YBTopaz8** [comment]
Thanks for the update! I'll get it whenever possible even if it's in preview.

And yeah, from what I read, borders would be more lightweight even though it has really cool features like shadows.

Thanks again!

**Comment by enisn** [comment]
I released a stable version instead preview version by a mistake, but I'm sure it's more stable than v2.6 🙂
