### ISSUE TITLE
[Android] InputFields have a line in net8.0

### ISSUE THREAD

**Issue by StepKie** [enisn/UraniumUI#490]
Upgrading an app to net8.0 adds a line to the input field

net7.0
<img width="386" alt="Screenshot 2023-11-23 164740" src="https://github.com/enisn/UraniumUI/assets/17760200/026f4d52-ad02-47cf-9647-2f064fd81cef">

net8.0
<img width="388" alt="image" src="https://github.com/enisn/UraniumUI/assets/17760200/d8db00a1-0db9-4ced-9ee9-ccccbb368710">

Unfortunately, this prevents us from upgrading altogether.
I did not test on iOS.

**Comment by enisn** [comment]
Which version do you use on .NET8?

**Comment by StepKie** [comment]
The latest available on the public nuget feed I think:

```
<PackageReference Include="UraniumUI.Icons.MaterialIcons" Version="2.5.6" />
<PackageReference Include="UraniumUI.Material" Version="2.5.6" />
```

**Comment by enisn** [comment]
If you go with .NET8, you should use v2.6.0-pre.3

I'll release a stable version soon, but for now, v2.6 is compiled with .NET8

**Comment by StepKie** [comment]
Oh, I was not aware of that.

That fixes it, thank you very much!
