### ISSUE TITLE
Implicit label styles not applied within ButtonView

### ISSUE THREAD

**Issue by pikausp** [enisn/UraniumUI#493]
When I have a `Label` within a `ButtonView` it does not respect the implicit styles defined on the page (or the app). I have to use the feature cascading styles to get this working. I believe this behavior is quite tricky. Is it by design or is it a bug? Would you consider not blocking implicit styles if the behavior is by design?

```
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:material="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
             xmlns:t="clr-namespace:UraniumUI.Theming;assembly=UraniumUI"
             x:Class="UraniumStyleIsolation.MainPage">
    <ContentPage.Resources>
        <Style TargetType="Label">
            <Setter Property="TextColor" Value="Red"/>
        </Style>

        <Style TargetType="material:ButtonView" Class="Cascading">
            <Setter Property="t:CascadingStyle.Resources">
                <ResourceDictionary>
                    <Style TargetType="Label">
                        <Setter Property="TextColor"  Value="Blue" />
                    </Style>
                </ResourceDictionary>
            </Setter>
        </Style>
    </ContentPage.Resources>

    <ScrollView>
        <VerticalStackLayout
            Padding="30,0"
            Spacing="25">

            <Label Text="Test"/>

            <material:ButtonView StyleClass="Cascading">
                <Label Text="Test"/>
            </material:ButtonView>

            <material:ButtonView>
                <Label Text="Test"/>
            </material:ButtonView>
        </VerticalStackLayout>
    </ScrollView>

</ContentPage>
```

![image](https://github.com/enisn/UraniumUI/assets/6717146/5823e0ea-acb2-46bf-beb2-762d372c671d)

Repro repo https://github.com/pikausp/UraniumStyleIsolation

**Comment by enisn** [comment]
Hi, This was the tough problem that I faced building styling system. MAUI can't get multiple styles hierarchical by default like CSS. It get the nearest style and stops checking in higher levels. So, merging two different styles for the same component was not possible.

I'm not sure if it works and I'll check when I find some time.
But can you try setting `CanCascade="True"` for your style? Probably it prevents getting the nearest and merges original style with yours. 

I'll try and find a solution asap

**Comment by enisn** [comment]
Nope, sorry, I need to add `CanCascade="True"` for this label style:

https://github.com/enisn/UraniumUI/blob/d5c7fe518c6f3d4d9dccf2ddd915836e7cdf3b51/src/UraniumUI.Material/Resources/StyleResource.xaml#L342

**Comment by pikausp** [comment]
Thanks for the update. So it's something that will be fixed in the upcoming release, yeah?

**Comment by enisn** [comment]
Yes, I'll include this change in the next release 👍
