### ISSUE TITLE
Wrapping elements inside a container

### ISSUE THREAD

**Issue by David-Moreira** [enisn/UraniumUI#514]
What's the recommended way to wrap uranium ui elements inside a container with a background and a border?

I was trying to use the Frame with one of the Uranium UI style classes, but everything just gets overwritten 
https://enisn-projects.io/docs/en/uranium/latest/themes/material/Containers

```
        <Frame BackgroundColor="Transparent" StyleClass="TertiaryContainer">
            <mc:TextField
                Title="Nome"
                Icon="{FontImageSource FontFamily=MaterialRegular,
                                       Glyph={x:Static fonts:MaterialRegular.Person}}"
                Text="{Binding UserName, Mode=TwoWay}" />

        </Frame>
```
The text field will not be visible at all. I tried modifying the ZIndex, but maybe I'm not using this correctly at all.
![image](https://github.com/enisn/UraniumUI/assets/22283161/b737b0ed-f455-400e-a162-b79d30ae572f)

Appreciate the help.

**Comment by enisn** [comment]
https://github.com/enisn/UraniumUI/issues/481#issuecomment-1814390941

Please avoid using `Frame` until the solution of https://github.com/dotnet/maui/issues/18526

Can you try using `Border` instead frame? If you need shadow from frame, you can use [Elevation](https://enisn-projects.io/docs/en/uranium/latest/themes/material/Elevation) classes like the following example:
https://enisn-projects.io/docs/en/uranium/latest/migration-guides/Migrating-To-2.7#changes
```xml
<Border StyleClass="SurfaceContainer,Rounded,Elevation1">
    <!-- You old Frame content -->
</Border>
```

**Comment by David-Moreira** [comment]
I see, I'll follow your advice. Really appreciated. You are free to close this issue if you are already aware of the issue and following it.

**Comment by David-Moreira** [comment]
On a side note it seems like the title for the migration page for 2.7 mught be wrong If you have time to fix it.

**Comment by enisn** [comment]
> On a side note it seems like the title for the migration page for 2.7 mught be wrong If you have time to fix it.

Thanks for the report, what a silly problem 😅 I've fixed it 👍
