### ISSUE TITLE
UraniumContentPage + CollectionView does not work

### ISSUE THREAD

**Issue by BeepBeepBopBop** [enisn/UraniumUI#519]
Hi, I tried to use UraniumContentPage but noticed that it won't work properly with CollectionView.

The following XAML structure will show an empty page, although it works with MAUI base ContentPage:
 
```
<u:UraniumContentPage>>
        <Grid>
            <CollectionView>

            </CollectionView>
        </Grid>
    </u:UraniumContentPage>
```

**Comment by enisn** [comment]
Hi did you use Frame in the Page or inside DataTemplate of CollectionView?

**Comment by BeepBeepBopBop** [comment]
Hey, thanks for getting back to me and sorry I did not catch that earlier. I tackled the issue for the last couple hours to provide you with a fully reproducible code sample and scratched my head quite a lot until I noticed the issue was gone simply by updating the package to the latest version...

For the record it had to do with the Border control, and only on Android, with the package version 2.5.6. Anyway I will be happily using UraniumContentPage now, happy new year :)
