### ISSUE TITLE
https://enisn-projects.io/ - documentation not available (HTTP ERROR 500)

### ISSUE THREAD

**Issue by get-flat** [enisn/UraniumUI#527]
Can you please point me to working docs

**Comment by davidblaine228** [comment]
I also noticed that it doesn't work, thought it was something on my end.
Yesterday it was saying "host unreachable," now it's error 404

**Comment by andyzukunft** [comment]
I was just about to report this myself :-)

I think you can access the documentation directly from github: https://github.com/enisn/UraniumUI/tree/develop/docs/en

**Comment by enisn** [comment]
It should be working now, sorry I couldn't take an action at weekend 👍

**Comment by shown1985** [comment]
it's 404 now 
http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material
