### ISSUE TITLE
Update the material icon fonts

### ISSUE THREAD

**Issue by Dokug** [enisn/UraniumUI#542]
Seing as the last update to the material icon font files happened 2 years ago, I would suggest updating them to their current version which can be found [here](https://github.com/google/material-design-icons/tree/master/font).

If you'd like me to, I can create a pull request for that myself.

Thank's for your work!

**Comment by enisn** [comment]
Yes, I marked this issue as '**good first issue**, you can send a PR for this

**Comment by Dokug** [comment]
This was closed by #546

**Comment by enisn** [comment]
Thanks for the contribution 🎉

Old Material Icons support will be dropped in the next versions, but for a time I'll keep that library to prevent forcing breaking changes in the projects that uses old one
