### ISSUE TITLE
Include the Material Symbols fonts

### ISSUE THREAD

**Issue by Dokug** [enisn/UraniumUI#545]
As Google does not seem to be updating the "Material **Icons**" fonts anymore and recommends switching to the "Material **Symbols**" fonts (as can be seen [here](https://github.com/google/material-design-icons/tree/master/font)), I would suggest adding the Material Symbols font either as a separate project or as an addition to the already existing UraniumUI.MaterialIcons project.

I can try to put together a PR for a seperate UraniumUI.MaterialSymbols project, if you'd want me to.
The Material Symbols fonts can be found [here](https://github.com/google/material-design-icons/tree/master/variablefont).

**Comment by enisn** [comment]
That makes sense, We can create another assembly for this symbols to prevent breaking changed for the current ones. I can be named as `UraniumUI.Icons.MaterialSymbols` and Icons library will be deprecated

**Comment by maico-todi** [comment]
@Dokug @enisn Is there a way to make use of the `UraniumUI.Icons.MaterialSymbols` using the Filled style?

**Comment by Dokug** [comment]
Currently I don't think so.
I would need to look into that, but I think the "filled" style is a separate font.
