### ISSUE TITLE
PickerField

### ISSUE THREAD

**Issue by JamesSonic** [enisn/UraniumUI#547]
Hello, 

I'm trying to set the pickerFields selectedItem. But I can't seem to get this to work. Has anyone done this?

`<material:PickerField   
      SelectedItem="5" 
      ItemsSource="{Binding Source={RelativeSource AncestorType={x:Type local:ProcessViewModel}}, Path=Prices}" 
      Margin="10"  x:Name="Price" Grid.Row="0"  Grid.Column="2"  
      SelectedValueChanged="Price_OnSelectedValueChanged"  Title="{x:Static res:AppResources.Price}"  AllowClear="False" >
     <validations:RequiredValidation Message="{x:Static res:AppResources.RequiredError}" />
</material:PickerField>`
                             
         
         `    public static List<int> Prices = new List<int>
    {
        0, 5, 10, 15, 20, 25, 30, 35, 40, 45,
        50, 55, 60, 65, 70, 75, 80, 85, 90, 95, 100
    };
`

**Comment by michael-b-tt0** [comment]
What is the correct method signature for the SelectedValueChanged event here?
