### ISSUE TITLE
How to make a breadcrumb navigation bar?

### ISSUE THREAD

**Issue by roxxxxssss** [enisn/UraniumUI#557]
I want to create a flat breadcrumb navigation system like an Android system, Can you teach me something? thanks

**Comment by roxxxxssss** [comment]
refenrence address : https://webartdevelopers.com/blog/css3-breadcrumb/

**Comment by enisn** [comment]
Breadcrumb implementation doesn't exist currently and it's not included in the backlog right now.

I'm not sure implementing it inside UraniumUI, there is already a good implementation for MAUI. 
You can try this: https://github.com/IeuanWalker/Maui.Breadcrumb

**Comment by roxxxxssss** [comment]
Okay, thank you. Let me take a look
