### ISSUE TITLE
TabView Items do not use dependency Injection

### ISSUE THREAD

**Issue by WoistdasNiveau** [enisn/UraniumUI#567]
Dear Community!

I wanted to use the TabView instead of the Shell TabView as it gives more room for customization, however, it cannot use Dependency injection when used in xaml. Is there planned to bring in the support for this? As Shell can inject the ViewModel for example in the constructor of the View it would be nice for these Tabs as well.

With regards

**Comment by enisn** [comment]
Hi, 

**TabView** is a `View` not a `Page`. So, you can't resolve it from the dependency container. So, unfortunately, it's no possible with the default infrastructure of MAUI.

But there are 2 different approaches I can show you in UraniumUI:

### 1. Uranium Inject
`Inject` is an XAML extension for resolving a service from Service Collection to a view, and you can  use it like binding logic in the xaml:

```xml
        <material:TabView BindingContext="{uranium:Inject Type={Type vm:MyViewModel}}">
            <!--...-->
        </material:TabView>
```

### 2. UraniumServiceProvider

Some of UraniumUI components use dependency injection such as `MultiplePickerField` access `IDialogService` from service collection and open a dialog. If you need to resolve from C# side, this might fit your situation

https://github.com/enisn/UraniumUI/blob/48719b07ed0dc8fa3eba64407491a5ff8cd2002a/src/UraniumUI.Material/Controls/MultipleSelectionField.cs#L52

It's not a recommended way but you can use `UraniumServiceProvider` to resolve a service from a view like below:

```cs
var viewModel = UraniumServiceProvider.Current.GetRequiredService<MyViewModel>();
```

**Comment by WoistdasNiveau** [comment]
That makes a lot of sense thank you very much
