### ISSUE TITLE
DataGrid not showing TitleView with empty List

### ISSUE THREAD

**Issue by WoistdasNiveau** [enisn/UraniumUI#569]
Dear Community!

Is it possible to add that per default the TitleView of the Datagrid appears even though the List behind is empty when Titles are set for each DataGridColumn? 

With regards,
Oliver

**Comment by enisn** [comment]
Hi, this problem occurs because of AutoColumns property. When it's set as true, it can't know properties from an empty collection.

But, when columns are defined in XAML, we can show headers only. I'll consider it.
