### ISSUE TITLE
DataGrid questions

### ISSUE THREAD

**Issue by MaxFaber90** [enisn/UraniumUI#58]
Hello,
I'm trying to use the Datagrid component into a MAUI project. Unfortunately I'm facing some speed issue during the binding of a large amount of records in View Model.
There is a way to speed up the process? Maybe a function of pagination or any type of virtualization. The application is really really slow. 

Thanks for your attention

**Comment by enisn** [comment]
DataGrid should have a paginatior component something like that:
![image](https://user-images.githubusercontent.com/23705418/192303291-e566e7b2-0f06-4657-813f-a7c5d55cc1c4.png)

I'm creating a new issue for Pagination & Sorting. Also, table headers should be clickable for sorting.

**Comment by acaliaro** [comment]
amazing @enisn

**Comment by MaxFaber90** [comment]
Thanks for the reply
Unfortunately right now I cannot find any command to paginate/sorting the grid.  There is a specific property in the control or it will be available in a future release?
Right now I'm using UraniumUI 13.0 and .NET MAUI

**Comment by enisn** [comment]
There is no option at the moment, it'll be a future feature. You can do it manually right now
