### ISSUE TITLE
Documentation Site HTTP Error 500

### ISSUE THREAD

**Issue by Nidoxs** [enisn/UraniumUI#584]
![image](https://github.com/enisn/UraniumUI/assets/75750304/d22677da-e46a-4125-93e1-f020f2388e35)

The documentation for UraniumUI does not seem to be working. Thought I'd make an issue to make you aware of it.

**Comment by enisn** [comment]
Solved now ✅

Sometimes problems may occur, you can check `docs` folder under this repository if you can't access the documentation website:
https://github.com/enisn/UraniumUI/tree/develop/docs/en
