### ISSUE TITLE
NullRef when creating AutoCompleteTextField with null Application.Current

### ISSUE THREAD

**Issue by TalipV** [enisn/UraniumUI#592]
My app has a NavigationPage code like this one here:
https://learn.microsoft.com/en-us/dotnet/maui/user-interface/pages/navigationpage?view=net-maui-8.0
```
public partial class App : Application
{
    public App()
    {
        InitializeComponent();
        MainPage = new NavigationPage(new MainPage());
    }
}
```

This means that during the creation of the MainPage instance the App instance is also in its creation phase -> Microsoft.Maui.Controls.Application.Current is null because it hasn't been set yet

Now, when the AutoCompleteTextField is created for the MainPage then following code in UraniumUI.Material.Controls.AutoCompleteTextField leads to a NullReferenceException: 
```
protected ContentView iconClear = new ContentView
{
	VerticalOptions = LayoutOptions.Center,
	HorizontalOptions = LayoutOptions.End,
	IsVisible = false,
	Padding = 10,
	Content = new Path
	{
		Data = UraniumShapes.X,
		Fill = ColorResource.GetColor("OnBackground", "OnBackgroundDark", Colors.DarkGray).WithAlpha(.5f),
	}
}
```
The reason for that is that **ColorResource.GetColor(...)** uses Application.Current without considering the null scenario -> AutoCompleteTextField ctor throws a NullReferenceException

**Comment by enisn** [comment]
The library is built on top of the [AppShell](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/create?view=net-maui-8.0) logic that resolves everything from dependency injection. So, this problem haven't been noticed yet. But you're right, this usage can be one of the approaches while development apps.

I'll try to handle this condition

**Comment by TalipV** [comment]
> The library is built on top of the [AppShell](https://learn.microsoft.com/en-us/dotnet/maui/fundamentals/shell/create?view=net-maui-8.0) logic that resolves everything from dependency injection. So, this problem haven't been noticed yet. But you're right, this usage can be one of the approaches while development apps.
> 
> I'll try to handle this condition

Thanks! Your fix is working fine.
