### ISSUE TITLE
DataGrid için Columns yönetilirliği (C# UI Markup)

### ISSUE THREAD

**Issue by gonultasmf** [enisn/UraniumUI#601]
akgul.maui.datagrid için :
```csharp
new Akgul.DataGrid()
.ItemsSourceFmg(BindingContext.Operations)
.ColumnsFmg(BindingContext.Columns)
.BackgroundColorFmg(Black)
.RowFmg(1) 
```
bu şekilde bir kullanım yapabiliyorum. Column yönetimine izin veriyor. 
Fakat UraniumUI için bu özellik bindableproperty olarak ayarlanmadığından yönetimi C# UI için sıkıntılı olabiliyor.

Dönüşünüz doğrultusunda FmgLib.MauiMarkup.Uranium kütüphanesinde güncelleme yapacağım. 

İyi çalışmalar.

**Comment by enisn** [comment]
Columns dinamik olarak planlanmadığı için sabit belirlenmesi gerekiyordu. Ancak dinamik bind olmasına hiçbir engel gözükmüyor. 

`Columns` için bir BindableProperty eklenebilir:
https://github.com/enisn/UraniumUI/blob/develop/src/UraniumUI.Material/Controls/DataGrid.BindableProperties.cs

**Comment by enisn** [comment]
Included in `2.9.0-pre.1` release
