### ISSUE TITLE
TextField icon + border = overlap title

### ISSUE THREAD

**Issue by xarlammm** [enisn/UraniumUI#602]
Hello, when using the icon and title, the border overlaps the title itself when in focus. How can I get around this?

I am attaching a screenshot.

![screen](https://github.com/enisn/UraniumUI/assets/95414457/78d30029-9960-4553-90f9-16fe069dc19b)

**Comment by enisn** [comment]
Can you share your usage?

Do you have **...AndExpand** LayoutOptions for any parent item of TextField? Like `FillAndExpand` or `CenterAndExpand`.

Since they're obsolete, they're not supported

**Comment by enisn** [comment]
Probably the same problem with https://github.com/malsabi/UraniumControlIssue/pull/1#issue-1931701910

**Comment by xarlammm** [comment]
Yes, indeed, I have used them. I tried to exclude all LayoutOptions, the problem remains. Here is the approximate structure of my XAML now:
[xaml.txt](https://github.com/enisn/UraniumUI/files/14492936/xaml.txt)

I also use my own icons.

**Comment by enisn** [comment]
Ok, one more information to reproduce the problem myself; 
On which platform do you face the problem?

**Comment by xarlammm** [comment]
Platform .NET MAUI 8

Target device Android 14
