### ISSUE TITLE
TextField - Add star to the required fields.

### ISSUE THREAD

**Issue by enisn** [enisn/UraniumUI#61]
Title should be `First Name *` when a `RequiredValidation` is included in the validations.
![image](https://user-images.githubusercontent.com/23705418/192462407-d3877bb3-cbcb-430b-82f1-f4802d3d885a.png)

**Comment by teeshajain17** [comment]
Hi, is this issue still open? I am new to open source, please let me know if I can work on this or any other issue. Thanks.

**Comment by enisn** [comment]
Yes, this is still open and isn't planned yet to work. It's in backlog, you can start contributions with this issue

**Comment by teeshajain17** [comment]
Thanks. Please assign this to me. I'll start working on this.

**Comment by teeshajain17** [comment]
Hi May I know on what page these fields exist?

**Comment by teeshajain17** [comment]
Hey, Do I need to implement this on Input Field Page?
Like this?
![image](https://user-images.githubusercontent.com/87597536/223377134-6d219112-6302-4e87-b0e9-332cb75bc518.png)
Or any other page?

**Comment by enisn** [comment]
I couldn't analyze it before. I'm not sure what is the best way to do it this screenshot seems good 👍

**Comment by teeshajain17** [comment]
Created the pull request for this change, please have a look
https://github.com/enisn/UraniumUI/pull/259

**Comment by StepKie** [comment]
@teeshajain17 this is not really what is needed here, you just hardcoded it in the sample application page?!
I have linked a PR for this

**Comment by teeshajain17** [comment]
Oh yeah, thanks.
