### ISSUE TITLE
Tab ordering/control in TextField

### ISSUE THREAD

**Issue by DevFromDownUnder** [enisn/UraniumUI#618]
Not sure if this would be an easy one to fix with the way MAUI is currently (i.e. no such thing as tabstops anymore).

If you have AllowClear enabled, tabing within the text field changes the focus to the clear button instead of the next control.
i.e. If you want to tab to the next field for entry, you have to tab twice

This breaks up the workflow and I have just been avoiding the clear button because of it.

**Comment by enisn** [comment]
It seems TabIndex was removed from MAUI with PR https://github.com/dotnet/maui/issues/1646

I'll take a look at it to find out what can be done.

**Comment by DevFromDownUnder** [comment]
Got a PR for this.

Not perfect but good enough.

Waiting on #634 PR to be incorped
