### ISSUE TITLE
Type 'FontImageSource' is used like a markup extension but does not derive from MarkupExtension

### ISSUE THREAD

**Issue by Permerkel** [enisn/UraniumUI#62]
Creating an Uranium project in Visual Studio 2022 leaves me with the following error in the XAML:

uranium:UraniumContentPage.Attachments>
        <attachment:BackdropView
                Title="Add" 
                IconImageSource="{FontImageSource FontFamily=MaterialRegular, Glyph={x:Static m:MaterialRegular.Add_circle}, Color={StaticResource OnPrimary}}"

The error is: Type 'FontImageSource' is used like a markup extension but does not derive from MarkupExtension

Please advice

BR

Per

**Comment by enisn** [comment]
I don't know if your IDE or dotnet workloads doesn't support `{FontImageSource ...}` usage.

Try updating workloads first:
```bash
dotnet workload install maui
```

If updating doesn't help, try using FontImages like this:
```xml
<Image>
  <Image.Source>
    <FontImageSource 
      FontFamily="MaterialRegular" 
      Glyph="{x:Static m:MaterialRegular.Add_circle}" 
      Color="{StaticResource OnPrimary}" />
  </Image.Source>
</Image>
```
