### ISSUE TITLE
Add a FontSize property to the AutoCompleteField, EditorField, and MultiplePickerField

### ISSUE THREAD

**Issue by codychaplin** [enisn/UraniumUI#620]
The TextField, PickerField, TimePickerField, and DatePickerField, all have a FontSizeProperty, yet the other input controls mentioned in the title do not. This would be greatly appreciated as it would add more consistency to the input fields. Love everything about UraniumUI, keep up the great work!

Cheers

**Comment by enisn** [comment]
Hi,

With the PR https://github.com/enisn/UraniumUI/pull/631, it'll be possible with styling:

```xml
<Style TargetType="Label" Class="InputField.Title">
    <Setter Property="FontSize" Value="Large" />
    <!--...-->
</Style>
```

It'll be released soon

**Comment by codychaplin** [comment]
Amazing, thanks!
