### ISSUE TITLE
Remove Tab Items in runtime

### ISSUE THREAD

**Issue by MohammedDastagir** [enisn/UraniumUI#626]
I'm using Uranium tabsview control and I have a feature to remove tab at runtime based on a condition. I tried below code

In my xaml :

      <material:TabView x:Name="tabsView">
           <material:TabItem Title="{StaticResource Icons.AttributeQuery}" HeaderTemplate="{StaticResource TabTemplate}">
               <material:TabItem.Content>
                   <dataAnalysis:AttributeQueryListView x:Name="attributeQueryListView"/>
               </material:TabItem.Content>
           </material:TabItem>
      </material:TabView>

and in my xaml.cs:

         tabsView.RemoveAt(0);
         tabsView.Children.RemoveAt(0)

I found only above two methods but it's not working. Is there any solution to this.

Any help is appreciated, thanks!

**Comment by enisn** [comment]
Normally **TabView** supports binding items like
```xml
<m:TabView ItemsSource="{Binding MyItems}"  />
<!-- or -->
<m:TabView Items="{Binding MyTabItems}"  />
```
When you add or remove items from collection, it automatically affects to TabView.

But still, you can remove them manually from C# code. Try the following way:
```csharp
        tabView.Items.Remove(tabView.Items[0]);
```

**Comment by MohammedDastagir** [comment]
@enisn Thanks for your response. Your solution worked like a charm.
