### ISSUE TITLE
How can I manipulate individual properties of a style Class?

### ISSUE THREAD

**Issue by andreas-spindler-mw** [enisn/UraniumUI#630]
Hi there!
I'm having a hard time adjusting individual properties on, as an example, `OutlinedButton` style class. I want to change the border width for all "OutlineButtons". But my changes either won't get applied, or I loose the existing outline button properties which I want to retain.
I know I can use the `StyleResource.Overrides` to overwrite entires styles. But that's not what I want. I'd like to extend an existing style class. How would I do that, without creating a second style `Class="ThickBorder"` which I would have to apply basically everywhere.

In App.xaml
```
<Application.Resources>
        <ResourceDictionary>
            <ResourceDictionary.MergedDictionaries>
                <ResourceDictionary x:Name="AppColors" Source="Resources/Styles/Colors.xaml" />
                <ResourceDictionary x:Name="AppStyles" Source="Resources/Styles/Theme.xaml" />
                <material:StyleResource
                    ColorsOverride="{x:Reference AppColors}"
                    BasedOn="{x:Reference AppStyles}">
                    <!-- <material:StyleResource.Overrides> -->
                    <!--     <ResourceDictionary Source="Resources/Styles/Theme.xaml" /> -->
                    <!-- </material:StyleResource.Overrides> -->
                </material:StyleResource>
            </ResourceDictionary.MergedDictionaries>
        </ResourceDictionary>
    </Application.Resources>
```

In Theme.xaml
```
<! -- overwriting the base style works -->
<Style TargetType="Button" BaseResourceKey="BaseButtonStyle">
        <Setter Property="CornerRadius" Value="0" />
        <Setter Property="BackgroundColor"
                Value="{AppThemeBinding
                Light={StaticResource SecondaryContainer},
                Dark={StaticResource SecondaryContainerDark}}" />
</Style>

<! -- Crashes the app, because OutlineButton is not found. How would I extend OutlineButton style class? -->
<Style TargetType="Button" Class="MyOutlinedButton" BasedOn="{StaticResource OutlineButton}">
        <Setter Property="BorderWidth" Value="5" />
</Style>
```

Any help is highly appreciated. Thank you guys!

**Comment by enisn** [comment]
Yeah, you can't use static resource from a different file in the current state of the application because the resources haven't been built and compiled yet. Can you try to define `BaseResourceKey` instead `BasedOn` property in the style?

```xml
<Style TargetType="Button" Class="MyOutlinedButton" BaseResourceKey="BaseButtonStyle">
```

But `OutlineButton` style **doesn't have** key in the library. So it's not possible to use it in this way. I'll add keys into library.

**Comment by andreas-spindler-mw** [comment]
Hi! Yes, I can do this, but this will of course apply a border to all buttons, and not just use a different border width on the outline buttons.
So, I understand that it is currently not possible to extend or change certain aspects of the current outline button style, right?

**Comment by DevFromDownUnder** [comment]
> Yeah, you can't use static resource from a different file in the current state of the application because the resources haven't been built and compiled yet. Can you try to define `BaseResourceKey` instead `BasedOn` property in the style?
> 
> ```
> <Style TargetType="Button" Class="MyOutlinedButton" BaseResourceKey="BaseButtonStyle">
> ```
> 
> But `OutlineButton` style **doesn't have** key in the library. So it's not possible to use it in this way. I'll add keys into library.

Added a pull for this

**Comment by andreas-spindler-mw** [comment]
Awesome! Thank you so much, for the immediate support!

**Comment by DevFromDownUnder** [comment]
Can be closed
