### ISSUE TITLE
CommandParameters on Custom DataGrid

### ISSUE THREAD

**Issue by YBTopaz8** [enisn/UraniumUI#65]
I've followed the steps from the documentations keenly, and have been able to implement a datagrid successfully with all my data loaded, thank you very much.
I have an issue that's been taking me hours and I can't seem to figure out a solution..
In the docs, the Command parameter is {Binding Data} as shown below.
but I scouted all the relevenat pages, viewmodels in order to determine what data, "Data" represents, but to no avail...
I wanted to implement an action button like in the doc's example, that will call a RelayCommand, and pass an object through it, which will then be used further.
I thought that "Data" represented a certain object, but i'm having a harding figuring, what object...
Here is an image of what I'm referring to from [here](https://github.com/enisn/UraniumUI/blob/develop/demo/UraniumApp/Pages/DataGrids/CustomDataGridPage.xaml) , line 71;
![image](https://user-images.githubusercontent.com/41630728/193440566-fa19775a-84ee-435f-9f77-e85e10dd65f8.png)

I would greatly appreciate some enlightening, please.
Thanks for everything once more.

**Comment by enisn** [comment]
Hi @YBTopaz8 

Each Datagrid cell has a Binding Context that is [CellBindingContext](https://enisn-projects.io/docs/en/uranium/latest/themes/material/components/DataGrid#cellbindingcontext).

| Property | Description |
| :--- | :--- |
| `Data` | The data of the cell item. |
| `Column` | The column number of the cell item. |
| `Row` | The row number of the cell item. |
| `Value` | The value of the cell item. _(You can bind it to the label directly)_ |
| `IsSelected` | Indicates whether the cell item is selected or not. |

According to that documentation, you can use a couple of properties for biding like `Row`, `Column` etc. 
`Value` means only that Cell's value, and `Data` means one of item in ItemsSource. 

As you can see in sample below, it's a student:
https://github.com/enisn/UraniumUI/blob/develop/demo/UraniumApp/Pages/DataGrids/CustomDataGridPageViewModel.cs#L36

**Comment by YBTopaz8** [comment]
Hello! And thank you for the swift reply.
I think I understood.
I can see that commands such as "Addnewcommand" and "RemoveItemCommand " are in the viewModel objects of ICommand, which, isn't the case in my point.
I usually perform these through methods.
I would like to know from you please, do you recommend using the same method as you? or is my approach (using methods) equally okay?

My simple idea is, I want that when the action button is clicked, the program gets the cell item ID and returns it. 
That's my idea.
Apologies for any inconvinience..

**Comment by enisn** [comment]
> ... is my approach (using methods) equally okay?

I can't say anything about how to build your application infrastructure well and which one fits your logic well. Sometimes you may want to use some MVVM Libraries and sometimes you'll only need simple methods.

If you go with binding commands as type of `ICommand`, this example shows about how it can be achieved.
https://github.com/enisn/UraniumUI/blob/develop/demo/UraniumApp/Pages/DataGrids/CustomDataGridPage.xaml

---

If you go with standard methods like setting a method to Clicked event of Button, that's also ok. You can always access CellBindingContext from the BindingContext of a cell.

```xml
<material:DataGridColumn Title="Actions" >
    <material:DataGridColumn.CellItemTemplate>
        <DataTemplate>
            <Button Text="Remove" 
                    BackgroundColor="{AppThemeBinding Light={StaticResource Secondary},Dark={StaticResource SecondaryDark}}" 
                    TextColor="{AppThemeBinding Light={StaticResource OnSecondary},Dark={StaticResource OnSecondaryDark}}"
                    Clicked="Button_Clicked"
                    />
        </DataTemplate>
    </material:DataGridColumn.CellItemTemplate>
</material:DataGridColumn>
```

```csharp
private void Button_Clicked(object sender, EventArgs e)
{
    if (sender is Button button)
    {
        Console.WriteLine(button.BindingContext);
    }
}
```

If you access to the bindingcontext of sender, you'll access to the CellBindingContext:

![image](https://user-images.githubusercontent.com/23705418/193646850-b8764bbf-b0c0-4b4a-b250-dc72e5da0972.png)


You can always use a check to make sure if the bindingcontext is CellBindingContext like this:

```csharp
private void Button_Clicked(object sender, EventArgs e)
{
    if (sender is Button button && button.BindingContext is CellBindingContext cellBindingcontext)
    {
        Console.WriteLine(cellBindingcontext);
    }
}
```

**Comment by YBTopaz8** [comment]
Incredible! Brilliant!.
Considering that I'm using communitytoolkit as my MVVM library, I will go ahead and use the "Button_clicked" Event and work my way with the cell binding context!
So far it's working as intended.
Thanks again for the assistance and for this awesome tool.
My question has been answered.
