### ISSUE TITLE
MultiplePickerField SelectedItems Change Event 

### ISSUE THREAD

**Issue by ruslan123456780** [enisn/UraniumUI#653]
Hi Team,

We are trying MultiplePickerField in our UI it is not supporting the  SelectionChange Event or not working Binding Property Change Event as well . Need the answer of possible solution or any release plan for it?

**Comment by enisn** [comment]
If you use ReactiveUI or something equivalent, you can handle changes of SelectedItem, or you can handle it in the setter of the observable property of your view model.

But still, we can add a regular C# event for that for simple usages.

**Comment by mstrong64** [comment]
I just looked at the source and there doesn't appear to be any command or event when the selected list changes. The single picker has an event and a command. Unfortunately I don't have time right now to submit a PR
