### ISSUE TITLE
AutoCompleteTextField doesn't work correctly when using explicit dependency resolution

### ISSUE THREAD

**Issue by codychaplin** [enisn/UraniumUI#654]
Long story short, I discovered that, at least on Android, the dropdown menu doesn't show up at all while typing when the ItemsSource is bound using a viewmodel that was set via `Handler.MauiContext.Services.GetService<>()`. [https://github.com/dotnet/docs-maui/blob/main/docs/fundamentals/dependency-injection.md#explicit-dependency-resolution](url)

I made a repo to test it here: [https://github.com/codychaplin/UraniumUITest](url). The AutoCompleteTextField works correctly when using constructor dependency injection, but not when using explicit dependency resolution. My repo shows the ItemsSource for 4 different AutoCompleteTextFields getting set in different ways. All ways work except for the one I described above.

**Comment by mglochsen** [comment]
I can confirm the issue for android. Changes to the ItemsSource are not recognized by the AutoCompleteTextField when it is an ObservableCollection and gets "refilled".

I can also provide a workaround: Instead of using an ObservableCollection I'm using a List now and replace the whole list.

```
public class TestViewModel : ObservableObject
{
    private IList<string> _data = [];

    public IList<string> Data
    {
        get => _data;
        private set => SetProperty(ref _data, value);
    }

    public void LoadData()
    {
        var newData = GetNewData();
        Data = new List<string>(newData);
    }
}
```

**Comment by enisn** [comment]
The problem occurs only on android since the handler creates a new instance of the list and can't get updated from ObservableCollection:
https://github.com/enisn/UraniumUI/blob/45896f701cdc3ecae48bfed9afcdc24fdf807015/src/UraniumUI/Handlers/AutoCompleteViewHandler.Android.cs#L101
