### ISSUE TITLE
Have keyboard extensions (show/hide keyboard) on text/entry views

### ISSUE THREAD

**Issue by YBTopaz8** [enisn/UraniumUI#674]
Just wondering if it's possible to have keyboard ext on those?
https://learn.microsoft.com/en-us/dotnet/communitytoolkit/maui/extensions/keyboard-extensions

Thanks

**Comment by enisn** [comment]
Sorry for late response, I couldn'T see this issue before.

You can access the actual entry by `EntryView` property of TextField.

```xml
<material:TextField Title="Name" x:Name="textField"/>
```

```csharp
textField.EntryView.HideKeyboardAsync(CancellationToken.None);
```

---
`TextField` exposes the actual entry for public usage. I should add this information to the documentation 👌👍
![image](https://github.com/enisn/UraniumUI/assets/23705418/5e73a766-72b9-4cd2-92fc-4ebe03e9f20b)
