### ISSUE TITLE
UraniumUI.Material components stopped rendering inside Frame in .NET 8.0.60

### ISSUE THREAD

**Issue by inimirpaz** [enisn/UraniumUI#678]
On upgrading to .NET 8.0.60 any child UraniumUI material component inside a `Frame` is not being displayed anymore.

I set up a Repro project here: https://github.com/inimirpaz/maui_issues/tree/uraniumui_issue_net8_0_60

```
    <StackLayout HeightRequest="250">
        <material:TextField Title="Hello" />
        <Frame BackgroundColor="Transparent" >
            <material:TextField Title="Hello" />
        </Frame>
    </StackLayout>
```

.NET 8.0.40:
![immagine](https://github.com/enisn/UraniumUI/assets/56956625/f152d119-b4d5-460e-a99f-25a1fada96b2)

.NET 8.0.60:
![immagine](https://github.com/enisn/UraniumUI/assets/56956625/bf836aaa-89b1-44c0-9a7c-1ab8cb00ba1d)

**Comment by enisn** [comment]
Frame is buggy in .NET MAUI, use Border instead

**Comment by enisn** [comment]
Same with https://github.com/enisn/UraniumUI/issues/481#issuecomment-1814390941

**Comment by inimirpaz** [comment]
See https://github.com/dotnet/maui/issues/23036
