### ISSUE TITLE
App Theme Settings are supported?

### ISSUE THREAD

**Issue by pallav1111** [enisn/UraniumUI#692]
App Theme Settings are supported with Uranium, If i Set `Light Mode` then `UraniumUI` are able to do changes accordingly?

**Comment by enisn** [comment]
Yes, UraniumUI implements colors with [AppThemeBinding](https://learn.microsoft.com/en-us/dotnet/api/microsoft.maui.controls.xaml.appthemebindingextension?view=net-maui-8.0) and it is built on top the default MAUI theming logic.

You can see in the demo application in the repository:

![uranium-dark-light](https://github.com/enisn/UraniumUI/assets/23705418/fd933231-fc75-49a5-95a6-df8f8f6cf02a)


It uses system theme by default or you can manually set requested theme in the code:
https://github.com/enisn/UraniumUI/blob/ddf2e6cef4efc12ac8266c2fd4e1799172cbec65/demo/UraniumApp/AppShell.xaml.cs#L17

**Comment by pallav1111** [comment]
Thanks @enisn for quick reply,

```
public AppShell(ILogger logger)
{
      InitializeComponent();
      App.Current.UserAppTheme = AppTheme.Light;
}
```
Device : Xiaomi Note 7S

it can not detect or callback on App.Current.RequestedThemeChanged when system theme changed.
And UraniumUI consider only PlatformAppTheme that cant be changed from MAUI side.
not working. is there anything other configuration are missing?
