### ISSUE TITLE
Bug Detected When Opening Two DisplayRadioButtonPromptAsync in Succession

### ISSUE THREAD

**Issue by GuyFlorent** [enisn/UraniumUI#695]
In my application, we first open a DisplayRadioButtonPromptAsync and retrieve the response. Then, we open another DisplayRadioButtonPromptAsync for a different result. Unfortunately, after opening the first one, the second one does not open, and the page becomes unresponsive. We cannot do anything except go back to the previous page. This is a blocking bug that prevents us from proceeding, making it very urgent.

**Comment by enisn** [comment]
Which dialogs package do you use?

[UraniumUI.Dialogs.CommunityToolkit](https://enisn-projects.io/docs/en/uranium/latest/dialogs/Index#communitytoolkit) or [UraniumUI.Dialogs.Mopups](https://enisn-projects.io/docs/en/uranium/latest/dialogs/Index#mopups) ?

If you use default implementation then it can be same problem with https://github.com/enisn/UraniumUI/issues/523 I suggest using **Mopups** or **CommunityToolkit**

**Comment by GuyFlorent** [comment]
i use [UraniumUI.Dialogs.Mopups](https://enisn-projects.io/docs/en/uranium/latest/dialogs/Index#mopups)
