### ISSUE TITLE
Bug with Mopups with Maui.CommunityToolkit 9.0.1 in release mode

### ISSUE THREAD

**Issue by GuyFlorent** [enisn/UraniumUI#696]
I recently updated the Maui.CommunityToolkit package to version 9.0.1, and since then, the application no longer compiles in release mode due to the MopUp package. However, reverting to the previous version 9.0.0 allows the release mode compilation to work correctly.

Could you please assist me in resolving this compatibility issue between Maui.CommunityToolkit 9.0.1 and MopUp so that I can use the latest version while maintaining the ability to compile in release mode?

Thank you in advance for your help.

**Comment by enisn** [comment]
I just updated CommunityToolkit dependency https://github.com/enisn/UraniumUI/pull/704

It is included in 2.9 preview release currently,
