### ISSUE TITLE
TextField on MacCatalyst still show the focus rectangle

### ISSUE THREAD

**Issue by rdurfee** [enisn/UraniumUI#726]
When a TextField gets focus on MacCatalyst, it shows a blue highlight border around the internal control.

The control's border is turned off, but the focus highlight is still there.

I was able to workaround it by setting `handler.PlatformView.FocusEffect`  to null in an Entry handler mapping.

<img width="977" alt="Screenshot 2024-07-31 at 11 25 47 AM" src="https://github.com/user-attachments/assets/abbeecd8-093c-479d-bb3a-d786ce0b4e72">

**Comment by enisn** [comment]
Hi, thanks for sharing the workaround too. I'll fix it in the library 🙏

**Comment by rdurfee** [comment]
I submitted a PR to fix this. Thanks for the great library!
