### ISSUE TITLE
Title text for text fields animates/ goes up every time page under tab is visited.

### ISSUE THREAD

**Issue by ketakidevendra** [enisn/UraniumUI#738]
If I have 2 Tabs, Tab1 is having Textfield with some value filled in it. So title is already at the top of text field.
When I click on Tab1 and then on Tab2 and revisit Tab1, Title animates and goes up every time leaving all UI distorted.

I am using a custom control which internally uses text field which has a command to navigate to other page and comes back to page.

![image](https://github.com/user-attachments/assets/1c149e2a-64fb-4095-ae6f-7efcb9dee642)
After clicking on Tab 2 and comong back to Tab1
![image](https://github.com/user-attachments/assets/11168405-5137-40a8-a8ff-0b807b272341)

Findings from @enisn  regarding this issue as mentioned in [this](https://github.com/enisn/UraniumUI/issues/716#issuecomment-2283765523) issue.
It happens because of technical limitations. It releases events when removed from layout and re-registers when it's visible again. Since the locations are set by an animation, they're re-animated when become visible. You can create another issue for this problem. Maybe I can handle page rendering and set label position without animating

**Comment by ketakidevendra** [comment]
Any update on this @enisn. This is affecting my app.

**Comment by StepKie** [comment]
Any update on this @enisn ?

**Comment by enisn** [comment]
> Any update on this @enisn ?

I made an enhancement for a better transition between switching tabs with #755
