### ISSUE TITLE
Filled Style for Material Symbols

### ISSUE THREAD

**Issue by scheidtdav** [enisn/UraniumUI#739]
After my PR #735 the other day, I realized that there are already filled variants of the MaterialSymbols available as a .ttf in the project.
It doesn't say anywhere in the docs on how to use it though and my original change of the docs completely ignores that.

Going down the rabbit hole, I noticed a bunch of things:
- The .ttf file used for the non-filled variant is the raw .ttf file handed out by Google measuring a cool 11MB in size because it contains every variant
- The .ttf file of the current filled variants contain a bunch of Glyphs not present in the non-filled variants
  - Probably a different version was used in #621 
- Filled and non-filled .ttfs use the same codepoints for the Glyphs so its not necessary to have them in the code 6 times

So I am proposing to change the following:
- Use one generated .ttf file per style
  - I simply ran e.g. `fontTools varLib.mutator MaterialSymbolsSharp[FILL,GRAD,opsz,wght].ttf` without any additional parameters to get just the default look (non-filled). That reduces the size to about 1MB per variant
- Just keep `MaterialOutlined`, `MaterialRounded` and `MaterialSharp` as classes and select the filled look by changing the FontFamily to e.g. `MaterialOutlinedFilled`

I have a PR ready with the above proposal including an update to the docs.
Sorry if thats the wrong order, I just read the contribution guidelines after going down the rabbit hole 🙈 

Let me know if there is anything to change here!

**Comment by enisn** [comment]
Thanks for your effort 🥳 I'll check it and merge as soon as possible
