### ISSUE TITLE
Bindable AutomationIds in InputFields and maybe some other controls are missing

### ISSUE THREAD

**Issue by KonstantinKellermann** [enisn/UraniumUI#753]
We are experiencing issues when trying to run UI tests using Appium for our .NET MAUI application, where we use UraniumUI.Material version 2.9.1.

We are facing problems with TextField and other UraniumUI controls. Appium can detect the AutomationId, but it seems like the AutomationId is set incorrectly — it appears it is set to the Grid the InputField inherits from and not the actual input field. As a result, Appium cannot interact with the TextField to write input.

We created a custom TextField based on the UraniumUI TextField and added a BindableProperty for setting the AutomationId. This solution worked for us and allowed Appium to interact correctly with the control.

Proposal: The BindableProperty for the AutomationId should be set inside the controls like TextField and EditorField and potentially other UraniumUI controls, to ensure proper interaction in UI tests.

**Comment by z3t444** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
