### ISSUE TITLE
Binding datagrid itemsource to ObservableCollection<ExpandoObject> 

### ISSUE THREAD

**Issue by ChristofferKJ** [enisn/UraniumUI#76]
When i bind the itemsource to an ObservableCollection of ExpandoObjects and try to generate auto columns, nothing happens. Has anyone had any luck with binding to these objects?

**Comment by enisn** [comment]
AutoColumns searches for properties of the object.
https://github.com/enisn/UraniumUI/blob/b200486accc8c4ad769117090a4055a329412d46/src/UraniumUI.Material/Controls/DataGrid.cs#L120-L126

But, **ExpandoObject** doesn't have physical property members. ExpandoObject behaves like `IDictionary<String, Object>`,
So, you can not know properties when there is no data in the collection. Also, each item can have different properties in this collection. You need an instance to understand which properties are available. If ItemsSource is empty and the count is 0, you'll never know which properties exist and which columns to render.

https://learn.microsoft.com/en-us/dotnet/api/system.dynamic.expandoobject?view=net-7.0#enumerating-and-deleting-members
You can enumerate properties but what if the collection items count is zero?

**Comment by ChristofferKJ** [comment]
Thanks a lot for your reply :) 

Alright. I will try to do something else for it to work then. 
Is it possible to use a DataTable as ItemSource?

**Comment by enisn** [comment]
You can inherit from `DataGrid` and implement your own column logic:
```csharp
public class MyDataGrid : DataGrid
{
    protected override void SetAutoColumns()
    {
        if (UseAutoColumns)
        {
            // 👇 You can set whatever you want as columns here
            Columns = GetColumns(CurrentType); 

            Render();
        }
    }

    private List<DataGridColumn> GetColumns(Type type)
    {
        return // Your columns logic
    }
}
```

**Comment by ChristofferKJ** [comment]
@enisn  Thanks a lot. I got it to work :)
