### ISSUE TITLE
TextField in UraniumUI.Material 2.10.0: BorderColor not working properly and InputBackgroundColor ignored

### ISSUE THREAD

**Issue by inimirpaz** [enisn/UraniumUI#775]
Hello,

   Github repro: https://github.com/inimirpaz/maui_issues/tree/uraniumui_entry_issue

![ezgif-1-15b9dc1a1b](https://github.com/user-attachments/assets/2c4cb397-cd92-4afd-ae08-2d0ff3cf6420)

With the latest 2.10.0 release the BorderColor of the Entry component has stopped working properly. Now it is not set until the control receive focus at least once. At least in Android but not tested on iOS.

Also, I noticed a property called InputBackgroundColor which I thought could be like the backgroundcolor but clipped by the rounded borders of the entry (which would be great if it were possibile, since the BackgroundColor is not clipped), but it does nothing.

Thank you

**Comment by enisn** [comment]
Might be related to https://github.com/enisn/UraniumUI/pull/728
or https://github.com/enisn/UraniumUI/pull/760

**Comment by enisn** [comment]
Does it work in the previous version?

**Comment by inimirpaz** [comment]
> Does it work in the previous version?

Yeah, and the InputBackgroundColor indeed works (I did not notice this property before, so I am experiencing it working for the first time here).

![immagine](https://github.com/user-attachments/assets/38e1928c-055f-4dd3-89ff-a3d95ed0d072)

**Comment by inimirpaz** [comment]
Actually I noticed that there is still a problem back in 2.9.1: the placeholder was not shown until the control got the focus.

![ezgif-1-e8ea8d75d0](https://github.com/user-attachments/assets/e697fa55-89ae-4bf8-90c0-eb1738202559)
