### ISSUE TITLE
Visual bug MultiplePickerField when binding data

### ISSUE THREAD

**Issue by wout1511** [enisn/UraniumUI#777]
when I go to a page with a multipicker where the multipicker is populated with data, there is a visual bug that the title does not go up as it should

![image](https://github.com/user-attachments/assets/297b3a42-27a3-48ca-8cb1-61916c87ed96)

After resizing the page, the multipicker goes to normal

![image](https://github.com/user-attachments/assets/6271248c-7374-4e56-bd24-1a276ba7a0ff)

**Comment by enisn** [comment]
Might be related to https://github.com/enisn/UraniumUI/pull/768

Can you try the previous version _(v2.9.1)_? Probably this problem exists in the latest release

**Comment by enisn** [comment]
Hi @wout1511 

I can't reproduce the same behaviour:

I tried both Binding from ViewModel and setting static items in XAML and it worked as expected.
![image](https://github.com/user-attachments/assets/635e2239-60ac-4eae-98d2-d161fa087bdf)

Can you try to update the latest version?
If you still reproduce the issue, please provide reproduction steps

**Comment by wout1511** [comment]
Hello @enisn,
I upgraded to the latest version but it did not fixed the bug.
These are my bindings:
![image](https://github.com/user-attachments/assets/f7e947b1-a651-4078-ab49-4623c367ce77)
![image](https://github.com/user-attachments/assets/7bf0bda1-6cac-45e2-9b27-e51d5876ff62)

**Comment by enisn** [comment]
> Hello @enisn, I upgraded to the latest version but it did not fixed the bug. These are my bindings: ![image](https://private-user-images.githubusercontent.com/144464682/371010257-f7e947b1-a651-4078-ab49-4623c367ce77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzMjMsIm5iZiI6MTcyNzM0MTAyMywicGF0aCI6Ii8xNDQ0NjQ2ODIvMzcxMDEwMjU3LWY3ZTk0N2IxLWE2NTEtNDA3OC1hYjQ5LTQ2MjNjMzY3Y2U3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2I4Njc1YWU1YjI1NTg4OTMwY2Y4YTc3MzBmYTdmZTAzYWRlMTQwNTU0NTMyNzVjNDZmNmFjODMxYjFiMTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DJOdWnRo5qhaafPyaFF9SvwbJOm00IR-M3dRnlwNYXs) ![image](https://private-user-images.githubusercontent.com/144464682/371010318-7bf0bda1-6cac-45e2-9b27-e51d5876ff62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzMjMsIm5iZiI6MTcyNzM0MTAyMywicGF0aCI6Ii8xNDQ0NjQ2ODIvMzcxMDEwMzE4LTdiZjBiZGExLTZjYWMtNDVlMi05YjI3LWU1MWQ1ODc2ZmY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQ4YWJlNjZiMzkxNzM1NmQ2M2I2Y2JiZTExMjk4YzAxZjMzMDA4YTMzNDZhMGQ3MGQyMzE5YmE0YjdhYzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YSA5fnHmuwGdLXhmkugiUx5n0uJkRQjGRpOYqxTvhoQ)

Is your page opened by `PushModalAsync` method, or it's a page inside AppShell?

**Comment by wout1511** [comment]
> > Hello @enisn, I upgraded to the latest version but it did not fixed the bug. These are my bindings: ![image](https://private-user-images.githubusercontent.com/144464682/371010257-f7e947b1-a651-4078-ab49-4623c367ce77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzMjMsIm5iZiI6MTcyNzM0MTAyMywicGF0aCI6Ii8xNDQ0NjQ2ODIvMzcxMDEwMjU3LWY3ZTk0N2IxLWE2NTEtNDA3OC1hYjQ5LTQ2MjNjMzY3Y2U3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2I4Njc1YWU1YjI1NTg4OTMwY2Y4YTc3MzBmYTdmZTAzYWRlMTQwNTU0NTMyNzVjNDZmNmFjODMxYjFiMTgxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.DJOdWnRo5qhaafPyaFF9SvwbJOm00IR-M3dRnlwNYXs) ![image](https://private-user-images.githubusercontent.com/144464682/371010318-7bf0bda1-6cac-45e2-9b27-e51d5876ff62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjczNDEzMjMsIm5iZiI6MTcyNzM0MTAyMywicGF0aCI6Ii8xNDQ0NjQ2ODIvMzcxMDEwMzE4LTdiZjBiZGExLTZjYWMtNDVlMi05YjI3LWU1MWQ1ODc2ZmY2Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNlQwODU3MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjQ4YWJlNjZiMzkxNzM1NmQ2M2I2Y2JiZTExMjk4YzAxZjMzMDA4YTMzNDZhMGQ3MGQyMzE5YmE0YjdhYzg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YSA5fnHmuwGdLXhmkugiUx5n0uJkRQjGRpOYqxTvhoQ)
> 
> Is your page opened by `PushModalAsync` method, or it's a page inside AppShell?

AppShell
