### ISSUE TITLE
Updating binding of Material TextField fails to move title of field until clicked

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#78]
When updating bindings of a Material:TextField, the title is not moved until the control is activated.

Example:
``` 
xmlns:material="clr-namespace:UraniumUI.Material.Controls;assembly=UraniumUI.Material"

<material:TextField
    Title="Name of Incident"
    Grid.Column="1"
    Margin="5"
    IsEnabled="{Binding Locked}"
    MaxLength="250"
    MaximumWidthRequest="200"
    Text="{Binding SelectedIncident.Name}" />
```
<img width="243" alt="image" src="https://user-images.githubusercontent.com/19739224/198199940-41ac0c27-4229-4f8f-89fe-a87b31d480d7.png">

After clicking control:
<img width="243" alt="image" src="https://user-images.githubusercontent.com/19739224/198199986-5dd10159-00f1-452f-bf83-f91082d667c9.png">

**Comment by enisn** [comment]
It's released in `v1.0.2` you can try the new version

**Comment by BinaryAssault** [comment]
> It's released in `v1.0.2` you can try the new version

Works great, thank you!

**Comment by BinaryAssault** [comment]
Should have mentioned, the same issue exists for the date and time picker fields. Sorry about that. Still exists in the latest version

**Comment by enisn** [comment]
Hi @BinaryAssault 
I couldn't reproduce this issue for other controls. Can you provide an example to reproduce it?

<img height="480" src="https://user-images.githubusercontent.com/23705418/198561617-6cfe89b6-2a57-41a7-9076-ff6a5b73bef2.gif" />

**Comment by BinaryAssault** [comment]
After further examination of my code, the issue was a binding issue. Works as intended. Thank you
