### ISSUE TITLE
Support DataAnnotations for FormView

### ISSUE THREAD

**Issue by listepo** [enisn/UraniumUI#82]
It would be good to use [DataAnnotations](https://learn.microsoft.com/ru-ru/dotnet/api/system.componentmodel.dataannotations?view=net-6.0) and [FormView](https://enisn-projects.io/docs/en/inputkit/latest/components/controls/FormView) together. For example [Devexpress](https://docs.devexpress.com/MAUI/403650/data-form/data-validation#data-annotations), [Mudblazor](https://mudblazor.com/components/form#editform-support)

**Comment by enisn** [comment]
That would be great. FormView can get the entire Model as parameter to check data annotations.
I'll consider it.

**Comment by enisn** [comment]
You can check the following documentation about using DataAnnotations with UraniumUI components:
https://enisn-projects.io/docs/en/uranium/2.0/validations/DataAnnotations

It's just released with `v2.0`
