### ISSUE TITLE
Title of TextField 

### ISSUE THREAD

**Issue by philldshaw** [enisn/UraniumUI#824]
After installing version 2.10.2 the titles of my TextFields display on top of the textfield entry text, but not always.
![image](https://github.com/user-attachments/assets/ca09429f-ebbc-4020-b874-2620fcc32f72)

This is my layout:
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage xmlns="http://schemas.microsoft.com/dotnet/2021/maui"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="AgentManagerMobile.Views.AgentAddressPage"
             xmlns:viewmodel="clr-namespace:AgentManagerMobile.ViewModels"
             xmlns:ur="http://schemas.enisn-projects.io/dotnet/maui/uraniumui/material"
             x:DataType="viewmodel:AgentAddressViewModel"
             
             Shell.TabBarIsVisible="False"             
             Title="Agent Address">

    <VerticalStackLayout
            Margin="0,20,0,0"
            Spacing="25"
            Padding="30,0"
            VerticalOptions="StartAndExpand">

        

        <Grid RowSpacing="0" ColumnSpacing="0" HorizontalOptions="Fill" VerticalOptions="Fill">
            <Grid.RowDefinitions>
                <RowDefinition Height="50" />
                <RowDefinition Height="70" />
                <RowDefinition Height="70" />
                <RowDefinition Height="70" />
                <RowDefinition Height="70" />
                <RowDefinition Height="70" />
                <RowDefinition Height="*" />
            </Grid.RowDefinitions>
            
        <ActivityIndicator 
            Grid.Row="0" Grid.RowSpan="7"
            HeightRequest="50" 
            WidthRequest="50"
            HorizontalOptions="Center"
            IsRunning="{Binding IsBusy}"
            IsVisible="{Binding IsBusy}"
            VerticalOptions="Center"
            Color="{StaticResource Primary}"/>

        <ur:TextField x:Name="Addr1" 
                      Grid.Row="1"
                      Text="{Binding Agent.Addr1,Mode=TwoWay}" 
                      Title="Address Line 1" 
                      Margin="5,0,0,0"      
                      HeightRequest="50" 
                      VerticalOptions="Center"
                      MaxLength="50"
                      AllowClear="True"/>

        <ur:TextField x:Name="Addr2" 
                      Grid.Row="2"
                      Text="{Binding Agent.Addr2,Mode=TwoWay}" 
                      Title="Address Line 2" 
                      Margin="5,0,0,0" 
                      HeightRequest="50"
                      VerticalOptions="Center"
                      MaxLength="50"
                      AllowClear="True"/>
        <ur:TextField x:Name="City" 
                      Grid.Row="3"
                      Text="{Binding Agent.City,Mode=TwoWay}" 
                      Title="City" 
                      Margin="5,0,0,0"  
                      HeightRequest="50"
                      VerticalOptions="Center"
                      MaxLength="20"
                      AllowClear="True"/>
        <ur:TextField x:Name="State" 
                      Grid.Row="4"
                      Text="{Binding Agent.State,Mode=TwoWay}" 
                      Title="State" 
                      Margin="5,0,0,0"  
                      HeightRequest="50"
                      VerticalOptions="Center"
                      MaxLength="50"
                      AllowClear="True"/>
        <ur:TextField x:Name="Zip" 
                      Grid.Row="5"
                      Text="{Binding Agent.Zip,Mode=TwoWay}" 
                      Title="Zip" 
                      Margin="5,0,0,0"  
                      HeightRequest="50"
                      VerticalOptions="Center"
                      MaxLength="10"
                      AllowClear="True"/>

        <Button Margin="0,20,0,0"
                Grid.Row="6"
                x:Name="SaveButton"
                Command="{Binding SaveCommand}"
                Text="Save" VerticalOptions="CenterAndExpand" 
                HeightRequest="50"
                WidthRequest="150"
                HorizontalOptions="FillAndExpand"/>

        </Grid>
    </VerticalStackLayout>
</ContentPage>

What could be causing this?
Thanks!

**Comment by mshenoy83** [comment]
Similar issue. I face it when I sometime hide and show a textfield

**Comment by Thiago-a1** [comment]
I have same issue with the PickerField
![Captura de tela 2024-12-03 143217](https://github.com/user-attachments/assets/ba3e4d52-63cc-436a-b466-490ac1989e27)

**Comment by StepKie** [comment]
Seems to be the same issue/ cause as #790.

Also highly critical issue for us...

**Comment by enisn** [comment]
I tried a couple of ways and couldn't reproduce, can you share a minimalist project hat can reproduce the issue? When it happens? While using AppShell or NavigationPage or just using simple ContentPage as MainPage?

**Comment by mikkdev** [comment]
The error occurs when an attempt is made to bind a string property from a ViewModel to a TextField. The bound value is expected to persist when navigating away from the current page and returning to it. 
However, the following problem occurs:
* Bind a string property from the ViewModel to the TextField.
* Enter some text into the TextField.
* Navigate away from the current page to another page.
* Navigate back to the original page.

**Comment by ketakidevendra** [comment]
@enisn - Are you able to reproduce this issue or do you still need sample project?

**Comment by enisn** [comment]
It happens only with PackageReference. When I try with the [UraniumApp](https://github.com/enisn/UraniumUI/tree/develop/demo/UraniumApp) with the local project reference it doesn't happen. That's why I couldn't reproduce it. I'm working on it but the most easiest solution is reverting the PR https://github.com/enisn/UraniumUI/pull/755

**Comment by enisn** [comment]
That was super silly race condition. When you pick an item, it unfocused from the PickerField immediately. At the same time, value also is changed. One animation applies unfocusing (moving title to the center), and another animation applies value selected animation (moving title to the top). Which one is started later than another decides the last position of the title.

This Pr solves the problem in a really easy way: #833
