### ISSUE TITLE
PickerField is not ReadOnly

### ISSUE THREAD

**Issue by BinaryAssault** [enisn/UraniumUI#83]
The textbox inside of the PickerField is not read only. Probably only a real problem on an emulator on a PC, but a keyboard can be left open after selection and data can be input into the picker field. A traditional picker doesn't allow editing the selected item.

Edit - its also a bug (mostly due to MAUI) without a PC. Simply create two controls, 1 that pops up a keyboard (editor/entry/textfield) and a picker. Click the editor/entry/textfield. Then without doing anything else, click the picker field. Select an item and then start typing on the soft keyboard that is still present (that is a MAUI bug, I believe, that keeps the keyboard open on unfocus).

**Comment by enisn** [comment]
I'll investigate it asap

**Comment by enisn** [comment]
This is also seems Android specific problem
