### ISSUE TITLE
TextField cannot be disabled

### ISSUE THREAD

**Issue by supershopping** [enisn/UraniumUI#85]
When I set the "IsEnabled" property of a TextField to false, it does not seem to work. 
Is this a bug? Thanks.

**Comment by BinaryAssault** [comment]
Duplicate of #81?

**Comment by supershopping** [comment]
Oh. I close this for now.

**Comment by supershopping** [comment]
Android:
I thought #85 will be fixed by #81, correct? The "IsEnable" still does not work with TextField as of 1.1 release. Did I miss anything?

**Comment by supershopping** [comment]
Sorry. It's working now. Somehow I didn't work on the first few times try out.

**Comment by enisn** [comment]
Make sure you applied migration guide

https://enisn-projects.io/docs/en/uranium/latest/migration-guides/Migrating-To-1.1

If you overrided styles in older versions, you should add disabled state of inputs
