### ISSUE TITLE
Unfocus() does not work on TextField 

### ISSUE THREAD

**Issue by supershopping** [enisn/UraniumUI#86]
Unfocus() does not work on TextField. How to unfocus and hide keyboard?

**Comment by BinaryAssault** [comment]
Might be related to [MAUI bug 4914](https://github.com/dotnet/maui/pull/4914)  and not UUI

**Comment by enisn** [comment]
I'll check this, most probably UUI doesn't pass state to the original MAUI control

**Comment by enisn** [comment]
Unfocus event isn't triggered on Android. It works on other platforms as expected. It seems it's related with https://github.com/dotnet/maui/pull/4914 as @BinaryAssault says

**Comment by supershopping** [comment]
The work around to trigger entry unfocus is to disable the text input and re-enable the control.  I am just waiting for the 1.1 release to have the disable feature. Thanks.

**Comment by enisn** [comment]
> The work around to trigger entry unfocus is to disable the text input and re-enable the control. I am just waiting for the 1.1 release to have the disable feature. Thanks.

I'll work on it
