### ISSUE TITLE
.NET 7 upgrade - error TapGestureRecognizer TreeView

### ISSUE THREAD

**Issue by bcaceiro** [enisn/UraniumUI#91]
Hi!
I've tried to use your package, with the latest .NET7 release for MAUI, however, when running a page with TreeView component, (iwindows target)  the following error appears:
Microsoft.Maui.Controls.TapGestureRecognizer.add_Tapped error 

After downgrading .NET7 to .NET6 all works without any issue. ( And yes, I know .net was released yesterday, so just wanted to leave a heads up!)

**Comment by enisn** [comment]
.NET 7.0 support will be released with v2.0

I'll prepare .NET 7.0 and release in this week.

**Comment by enisn** [comment]
https://github.com/enisn/UraniumUI/pull/92

**Comment by gpproton** [comment]
Also looking forward to this

**Comment by bcaceiro** [comment]
When using the TreeView on Windows / Mac & .NET7 we get this error/info -> Microsoft.Maui.Controls.Element: Warning: Microsoft.Maui.Controls.TapGestureRecognizer is already a child of Microsoft.Maui.Controls.ContentView. Remove Microsoft.Maui.Controls.TapGestureRecognizer from Microsoft.Maui.Controls.ContentView before adding to Microsoft.Maui.Controls.HorizontalStackLayout.

I am almost certain is related to the TreeView
